### ISSUE TITLE
/bin/sh: not found

### ISSUE THREAD

**Issue by Cascador** [termux/termux-app#104]
Hello,

I try to install Ansible.

```
apt update && apt upgrade
apt install autoconf make gcc openssl-dev libffi-dev python2-dev
pip2 install ansible
```

I have this issue.

`checking for GNU libc compatible malloc... yes
    checking for memmove... yes
    checking for memset... yes
    configure: creating ./config.status
    configure: 4915: configure: /bin/sh: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-kgCUm1/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-kgCUm1/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-kgCUm1/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    
    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python2 -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-kgCUm1/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-fTaev4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-kgCUm1/pycrypto
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

Tested with pip2 and pip3.

Thanks !

**Comment by bricewge** [comment]
Same issue with `pycrypto`here, when trying to `pip install salt`. And same trace.

**Comment by anthem** [comment]
I was able to install pycrypto by doing this first:

mkdir /data/data/com.termux/files/tmp
export BIN_SH=/system/bin/sh
export TMPDIR=/data/data/com.termux/files/tmp
export TMP=$TMPDIR
export TEMP=$TMPDIR

**Comment by anthem** [comment]
Update: You also need to set CONFIG_SHELL=/system/bin/sh

**Comment by bricewge** [comment]
@anthem: Thanks! I can't now install `pycrypto` via pip.

Note that`libgmp-dev` is also required.

**Comment by Cascador** [comment]
Not good for me. Always same error.

**Comment by Cascador** [comment]
Thanks ! Good for me finally ;)

**Comment by ShyPixie** [comment]
I have the same problem with gevent, and export CONFIG_SHELL or BIN_SH have no effect

**Comment by Neo-Oli** [comment]
@ShyPixie See this issue: https://github.com/termux/termux-packages/issues/283

**Comment by celikc** [comment]
i have same problem, i have applied all proposed command but i dont get any result 
I want to install pycrypto

**Comment by huitc** [comment]
https://blog.z4hd.cf/Install-gevent/
