### ISSUE TITLE
"termux-wake-lock" crashes termux 0.74

### ISSUE THREAD

**Issue by steffenl82** [termux/termux-app#1224]
I use termux with a FireTV stick. Running "termux-wake-lock" immediately crashes the termux app. This happened only after updating termux to v0.74 (v0.72 was running fine).

I guess this is the relevant logcat:

--------- beginning of crash
08-22 20:55:08.068  3757  3757 E AndroidRuntime: FATAL EXCEPTION: main
08-22 20:55:08.068  3757  3757 E AndroidRuntime: Process: com.termux, PID: 3757
08-22 20:55:08.068  3757  3757 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.termux.app.TermuxService@267e688 with Intent { act=com.termux.service_wake_lock cmp=com.termux/.app.TermuxService }: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:com.termux flg=0x10000000 }
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3365)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6188)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:com.termux flg=0x10000000 }
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:820)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:797)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at com.termux.app.TermuxService.onStartCommand(SourceFile:22)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3348)
08-22 20:55:08.068  3757  3757 E AndroidRuntime: 	... 8 more
08-22 20:55:08.112  3757  3757 I Process : Sending signal. PID: 3757 SIG: 9
08-22 20:55:09.212  6221  6221 W System  : ClassLoader referenced unknown path: /system/priv-app/MetricsApi/lib/arm
08-22 20:55:09.265  6221  6221 D AndroidRuntime: Shutting down VM

**Comment by TGWGitHub** [comment]
Same problem here.

Termux v0.74 on Samsung A500H running Android v6.0.1.

Termux v0.72 is the last known-good version without the issue.

**Comment by steffenl82** [comment]
I guess that this is caused by that change: https://github.com/termux/termux-app/pull/1216

**Comment by tomty89** [comment]
Solution: https://developer.android.com/guide/topics/manifest/uses-permission-sdk-23-element.html
@danog @xeffyr @fornwall

**Comment by xeffyr** [comment]
@tomty89 Are you sure that just changing permission will help ? We should probably handle `ActivityNotFoundException` when https://github.com/termux/termux-app/blob/94e5bc86fb12bdea8d00c00262a48b5e49236f40/app/src/main/java/com/termux/app/TermuxService.java#L123 is called.

**Comment by tomty89** [comment]
Hmm maybe some other stuff is broken as well (could be the ROMs themselves). Just noticed that it doesn't work on some Android M while it should.

There's no reason not to fix the permission though.

**Comment by danog** [comment]
Hmmm this actually makes sense because you're running on a TV stick, android TV sticks don't have batteries, they're powered directly via USB, so the ROMs wouldn't come with all the battery management logic that would otherwise be present on vanilla android.
Should've thought of this though, I too have one of these things laying around :)
#1238 should fix the issue, even if I don't think `-sdk-23` is of any use, since the app starts just fine.
