### ISSUE TITLE
command "am start <intent>" fails with missing app permission error

### ISSUE THREAD

**Issue by 3id0** [termux/termux-app#1318]
Thanks for making termux, it's Amazing.

**Problem description**

I'm trying to start a timer in the default Clock app via Termux and it fails because Termux doesn't have the following permission: `com.android.alarm.permission.SET_ALARM`

I went into the app settings (App permissions > All permissions) but this specific permission isn't in in the list of available ones and I don't see how or if it is possible for the end user to add a new custom permission to the Termux app.

**Steps to reproduce**

```
$ am start --user 0 -a android.intent.action.SET_TIMER
Starting: Intent { act=android.intent.action.SET_TIMER }
_TIMER }
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.example.termuxam.CrossVersionReflectedMethod.invoke(CrossVersionReflectedMethod.java:175)
        at com.example.termuxam.IActivityManager.startActivityAsUser(IActivityManager.java:165)
        at com.example.termuxam.Am.runStart(Am.java:635)
        at com.example.termuxam.Am.onRun(Am.java:353)
        at com.example.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.example.termuxam.Am.main(Am.java:74)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.SET_TIMER flg=0x10000000 cmp=com.android.deskclock/.HandleSetAlarmApiCalls } from null (pid=27214, uid=10070) requires com.android.alarm.permission.SET_ALARM
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.startActivityAsUser(IActivityManager.java:6845)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1782)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:725)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:551)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1156)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:490)
```

**Expected behavior**

I would like to be able to add new 'custom' app permissions to Termux, not just SET_ALARM but any permission I would need in the future.

**Comment by xeffyr** [comment]
> Termux doesn't have the following permission: com.android.alarm.permission.SET_ALARM

Yes, Termux doesn't have this permission.
It also won't be added officially because it is not needed for normal application functioning.

> I would like to be able to add new 'custom' app permissions to Termux

Not possible without modifying the app or rooting device. Permissions are managed by operating system (Android).

**Comment by 3id0** [comment]
Thanks for the quick answer.

I agree that this specific permission shouldn't be added officially.

I have a rooted device. Could you give me some pointers on how to add permissions with rooted device but without modifying the app, if possible ?

**Comment by trygveaa** [comment]
Can't permissions be requested on demand? Usually when I install an app nowadays, it doesn't get any permissions, and I get a popup asking for the permission when it's needed.

**Comment by xeffyr** [comment]
Permission should be declared in manifest.

> Or as a separate app, like Termux:API?

**Comment by 3id0** [comment]
`tsudo pm grant com.termux com.android.alarm.permission.SET_ALARM` returns `Security exception: Package com.termux has not requested permission com.android.alarm.permission.SET_ALARM`

**Comment by xeffyr** [comment]
> Security exception: Package com.termux has not requested permission com.android.alarm.permission.SET_ALARM

Then application should be modified unfortunately...

You may want to call Clock app's activity directly instead of using SET_TIMER intent. This should make permission granting unneeded.

**Comment by 3id0** [comment]
> You may want to call Clock app's activity directly instead of using SET_TIMER intent. This should make permission granting unneeded.

I want to pass the EXTRA_LENGTH, EXTRA_MESSAGE and EXTRA_SKIP_UI parameters to the timer so I think I have to use an intent in order to do that (?)

In any case, I tried calling the activity directly but I'm apparently not skilled enough to find the correct activity path. Here's what I tried:
```
# pm list packages | grep clock
package:com.android.deskclock

# pm path com.android.deskclock
package:/system/app/DeskClock/DeskClock.apk

# pkg install aapt

# aapt dump xmltree /system/app/DeskClock/DeskClock.apk AndroidManifest.xml | grep timer
        A: android:name(0x01010003)=".timer.ExpiredTimersActivity" (Raw: ".timer.ExpiredTimersActivity")
        A: android:name(0x01010003)="com.android.deskclock.timer.TimerReceiver" (Raw: "com.android.deskclock.timer.TimerReceiver")
        A: android:name(0x01010003)=".timer.TimerService" (Raw: ".timer.TimerService")

# am start -n com.android.deskclock/.timer.TimerService
Starting: Intent { cmp=com.android.deskclock/.timer.TimerService }
Error type 3
Error: Activity class {com.android.deskclock/com.android.deskclock.timer.TimerService} does not exist.

# am start -n com.android.deskclock/com.android.deskclock.timer.TimerReceiver
Starting: Intent { cmp=com.android.deskclock/.timer.TimerReceiver }
Error type 3
Error: Activity class {com.android.deskclock/com.android.deskclock.timer.TimerReceiver} does not exist.

# am start -n com.android.deskclock/com.android.deskclock.timer.TimerReceiver
Starting: Intent { cmp=com.android.deskclock/.timer.TimerReceiver }
Error type 3
Error: Activity class {com.android.deskclock/com.android.deskclock.timer.TimerReceiver} does not exist.

# am start -n com.android.deskclock/.timer.ExpiredTimersActivity
Starting: Intent { cmp=com.android.deskclock/.timer.ExpiredTimersActivity }
# # [Android quickly switches to another view and then back to Termux]

At this point I think I'll try something other than Termux for this job.
In any case thanks a lot for your help @xeffyr !

**Comment by 3id0** [comment]
> You may want to call Clock app's activity directly instead of using SET_TIMER intent. This should make permission granting unneeded.

I want to pass the EXTRA_LENGTH, EXTRA_MESSAGE and EXTRA_SKIP_UI parameters to the timer so I think I have to use an intent in order to do that (?)

In any case, I tried calling the activity directly but I'm apparently not skilled enough to find the correct activity path. Here's what I tried:
```
# pm list packages | grep clock
package:com.android.deskclock

# pm path com.android.deskclock
package:/system/app/DeskClock/DeskClock.apk

# pkg install aapt

# aapt dump xmltree /system/app/DeskClock/DeskClock.apk AndroidManifest.xml | grep timer
        A: android:name(0x01010003)=".timer.ExpiredTimersActivity" (Raw: ".timer.ExpiredTimersActivity")
        A: android:name(0x01010003)="com.android.deskclock.timer.TimerReceiver" (Raw: "com.android.deskclock.timer.TimerReceiver")
        A: android:name(0x01010003)=".timer.TimerService" (Raw: ".timer.TimerService")

# am start -n com.android.deskclock/.timer.TimerService
Starting: Intent { cmp=com.android.deskclock/.timer.TimerService }
Error type 3
Error: Activity class {com.android.deskclock/com.android.deskclock.timer.TimerService} does not exist.

# am start -n com.android.deskclock/com.android.deskclock.timer.TimerService
Starting: Intent { cmp=com.android.deskclock/.timer.TimerService }
Error type 3
Error: Activity class {com.android.deskclock/com.android.deskclock.timer.TimerService} does not exist.

# am start -n com.android.deskclock/com.android.deskclock.timer.TimerReceiver
Starting: Intent { cmp=com.android.deskclock/.timer.TimerReceiver }
Error type 3
Error: Activity class {com.android.deskclock/com.android.deskclock.timer.TimerReceiver} does not exist.

# am start -n com.android.deskclock/.timer.ExpiredTimersActivity
Starting: Intent { cmp=com.android.deskclock/.timer.ExpiredTimersActivity }
# # [Android quickly switches to another view and then back to Termux]

At this point I think I'll try something other than Termux for this job.
In any case thanks a lot for your help @xeffyr !
