### ISSUE TITLE
I can't build a apk

### ISSUE THREAD

**Issue by juamnitruh** [termux/termux-app#1740]
When i tried to build an apk (The sm64 android port), this shows up:
Exception in thread "main" java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;         at com.android.apksig.internal.apk.v1.V1SchemeSigner.generateManifestFile(V1SchemeSigner.java:378)                                                    at com.android.apksig.internal.apk.v1.V1SchemeSigner.sign(V1SchemeSigner.java:253)                  at com.android.apksig.DefaultApkSignerEngine.outputJarEntries(DefaultApkSignerEngine.java:657)                                                        at com.android.apksig.ApkSigner.sign(ApkSigner.java:436)                                            at com.android.apksig.ApkSigner.sign(ApkSigner.java:193)                                            at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:340)                                 at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)                          Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/data/com.termux/files/usr/share/dex/apksigner.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)                           at java.lang.ClassLoader.loadClass(ClassLoader.java:380)                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)                                            ... 7 more                                make: *** [Makefile:887: build/us_pc/sm64.us.f3dex2e.apk] Error 1

My phone is a lg k10, android 7.0

**Comment by xeffyr** [comment]
Fixed in latest build of `apksigner`.
