### ISSUE TITLE
pip install matplotlib always crashes

### ISSUE THREAD

**Issue by liyi93319** [termux/termux-app#1801]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-6joknq8r/matplotlib/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-6joknq8r/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-y76t568w
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-6joknq8r/matplotlib/
    Complete output (98 lines):
    WARNING: The wheel package is not available.
    ERROR: Exception:
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
        yield
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
        data = self._fp.read(amt) if not fp_closed else b""
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
        data = self.__fp.read(amt)
      File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 458, in read
        n = self.readinto(b)
      File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 502, in readinto
        n = self.fp.readinto(b)
      File "/data/data/com.termux/files/usr/lib/python3.9/socket.py", line 704, in readinto
        return self._sock.recv_into(b)
      File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
        status = self.run(options, args)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
        return func(self, options, args)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 155, in run
        requirement_set = resolver.resolve(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
        discovered_reqs.extend(self._resolve_one(requirement_set, req))
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
        abstract_dist = self.preparer.prepare_linked_requirement(req)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
        local_file = unpack_url(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 255, in unpack_url
        file = get_http_url(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 129, in get_http_url
        from_path, content_type = _download_http_url(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 282, in _download_http_url
        for chunk in download.chunks:
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 64, in response_chunks
        for chunk in response.raw.stream(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/data/data/com.termux/files/usr/lib/python3.9/contextlib.py", line 135, in __exit__
        self.gen.throw(type, value, traceback)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
        raise ReadTimeoutError(self._pool, None, "Read timed out.")
    pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmp7cjqhu5a', '--quiet', 'numpy>=1.15']' returned non-zero exit status 2.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-6joknq8r/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmp7cjqhu5a', '--quiet', 'numpy>=1.15']' returned non-zero exit status 2.
    
    Edit setup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (default, Oct  8 2020, 15:54:02)  [Clang 9.0.8
                      (https://android.googlesource.com/toolchain/llvm-project
                      98c855489]
        platform: yes [linux]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: no  [Mac OS-X only]
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

* Termux application version: 0.101
* Android OS version: 8.0.0
* Device model:

**Comment by Grimler91** [comment]
Looks like there is some problem with your internet connection?

Try installing `wheel` also (`pip3 install wheel`), and follow the wiki instructions if you still get problems: https://wiki.termux.com/wiki/Python#Python_module_installation_tips_and_tricks

**Comment by atharvabhanage12** [comment]
The problem is with the the version 3.9 . I had faced same problem . 
try doing it with any of the lower version i.e. 3.8.4  etc ....
