### ISSUE TITLE
Apksigner fails to verify

### ISSUE THREAD

**Issue by MrHeating** [termux/termux-app#1892]
When launching the following command: `$ apksigner verify "Signal-Android-website-prod-universal-release-5.1.9(1).apk"` The output looks like:

```
Exception in thread "main" java.io.FileNotFoundException: Signal-Android-website-prod-universal-release-5.1.9(1).apk: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:455)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:143)
        at com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:531)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
        at libcore.io.IoBridge.open(IoBridge.java:441)
        ... 4 more
```
Android 7, Termux 0,104 from F-Droid

The file is from here: https://signal.org/android/apk/

**Comment by xeffyr** [comment]
Ensure that file exist and is readable.

**Comment by MrHeating** [comment]
Turns out that Termux didn't have storage permissions and didn't ask/ let me know.

Now it returns a different error:
```
Exception in thread "main" java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
        at com.android.apksig.internal.asn1.Asn1BerParser.getElementType(Asn1BerParser.java:336)
        at com.android.apksig.internal.asn1.Asn1BerParser.access$000(Asn1BerParser.java:41)
        at com.android.apksig.internal.asn1.Asn1BerParser$BerToJavaConverter.setFieldValue(Asn1BerParser.java:570)
        at com.android.apksig.internal.asn1.Asn1BerParser$AnnotatedField.setValueFrom(Asn1BerParser.java:446)
        at com.android.apksig.internal.asn1.Asn1BerParser.parseSequence(Asn1BerParser.java:267)
        at com.android.apksig.internal.asn1.Asn1BerParser.parseSequence(Asn1BerParser.java:198)
        at com.android.apksig.internal.asn1.Asn1BerParser.parse(Asn1BerParser.java:138)
        at com.android.apksig.internal.asn1.Asn1BerParser.parse(Asn1BerParser.java:72)
        at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer.verifySigBlockAgainstSigFile(V1SchemeVerifier.java:494)
        at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(V1SchemeVerifier.java:309)
        at com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(V1SchemeVerifier.java:204)
        at com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(V1SchemeVerifier.java:126)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:294)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:149)
        at com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:531)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)
```
