### ISSUE TITLE
Termux keep crashing!

### ISSUE THREAD

**Issue by Z3wn** [termux/termux-app#1899]
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at com.termux.view.TerminalView.getProperties(SourceFile:7)
	at com.termux.view.TerminalView.onCreateInputConnection(SourceFile:1)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1660)
	at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1963)
	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2992)
	at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:151)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4676)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/issues/1896
