### ISSUE TITLE
Wrangler not installing

### ISSUE THREAD

**Issue by Ayan-Bhar** [termux/termux-app#1987]
I am trying to install [Wrangler](https://developers.cloudflare.com/workers/cli-wrangler)  with npm but it's showing an error!

```
npm i @cloudflare/wrangler -g
/data/data/com.termux/files/usr/bin/wrangler -&nbsp; /data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

&nbsp; @cloudflare/wrangler@1.15.0 postinstall /data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler
&nbsp; node ./install-wrangler.js

/data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler/binary.js:22
  throw new Error(`Unsupported platform: ${type} ${arch}`);
    ^
Error: Unsupported platform: Linux arm64
    at getPlatform (/data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler/binary.js:22:9)
        at getBinary (/data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler/binary.js:34:20)
            at install (/data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler/binary.js:51:18)
                at Object.<anonymous&nbsp; (/data/data/com.termux/files/usr/lib/node_modules/@cloudflare/wrangler/install-wrangler.js:4:1)
                    at Module._compile (internal/modules/cjs/loader.js:1063:30)
                        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
                            at Module.load (internal/modules/cjs/loader.js:928:32)
                                at Function.Module._load (internal/modules/cjs/loader.js:769:14)
                                    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
                                        at internal/main/run_main_module.js:17:47
                                        npm ERR! code ELIFECYCLE
                                        npm ERR! errno 1
                                        npm ERR! @cloudflare/wrangler@1.15.0 postinstall: `node ./install-wrangler.js`
                                        npm ERR! Exit status 1
                                        npm ERR!
                                        npm ERR! Failed at the @cloudflare/wrangler@1.15.0 postinstall script.
                                        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-04-02T17_01_53_831Z-debug.log
```

**Additional information**

* Termux application version: 0.101
* Android OS version: Android 10
* Device model: Redmi 9 Power (4GB Ram & 64GB Rom)

**Comment by Grimler91** [comment]
> Error: Unsupported platform: Linux arm64

Wrangler apparently does not support arm64 linux. That's not something we can fix, consider opening an issue in their repository.
