### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DasCodes1441** [termux/termux-app#2089]
hello.today i wanna open termux to play around with it but unexpectedly,it crashed.

btw here is the info termux collect about that event

## Report Info

**User Action**: `CRASH_REPORT`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2021-05-28 21:44:19 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2021-05-28 21:44:17 UTC`  

### Stacktrace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.termux.app.TermuxService.getTermuxSessionsSize()' on a null object reference
	at com.termux.app.terminal.TermuxTerminalSessionClient.addNewSession(TermuxTerminalSessionClient.java:196)
	at com.termux.app.TermuxActivity.lambda$setNewSessionButtonView$2(TermuxActivity.java:409)
	at com.termux.app.TermuxActivity.lambda$setNewSessionButtonView$2$TermuxActivity(Unknown Source:0)
	at com.termux.app.-$$Lambda$TermuxActivity$aOMOfOJf44c66QjcP3bxZ1lv8Oo.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7188)
	at android.view.View.performClickInternal(View.java:7165)
	at android.view.View.access$3500(View.java:814)
	at android.view.View$PerformClick.run(View.java:27651)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7815)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.112`  
**VERSION_CODE**: `112`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
##

### Software

**OS_VERSION**: `4.9.190+`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**INCREMENTAL**: `compiler05070018`  
**SECURITY_PATCH**: `2021-05-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `vivo`  
**BRAND**: `vivo`  
**MODEL**: `vivo 1938`  
**PRODUCT**: `1938`  
**DISPLAY**: `QP1A.190711.020 release-keys`  
**ID**: `QP1A.190711.020`  
**BOARD**: `k65v1_64_bsp`  
**HARDWARE**: `mt6765`  
**DEVICE**: `1938`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

the expected behaviour were to just run as usual.
and my device is not rooted and not using custom rom

that is all.i will reach you if it crashes again.hope it will be fine

**Comment by agnostic-apollo** [comment]
Thanks for the report. This was already fixed by [42ad3723](https://github.com/termux/termux-app/commit/42ad3723fd56c1b3db923eb3617e9107f7905813#diff-a4e61ecc5f3e6def38471e3d592e23fd1f1c2b2203aa4f9bcc97caa12ab38437L196). Update to [`v0.113`](https://www.reddit.com/r/termux/comments/ngtzsr/dev_termux_v0113_release/).
