### ISSUE TITLE
[Bug]: Termux crashed

### ISSUE THREAD

**Issue by OogleGlu** [termux/termux-app#2351]
### Problem description

Termux crashes on launch, including failsafe mode. Crash reporter doesn't come up with a crash report.

### Error
```
java.lang.SecurityException: Package com.termux.api does not belong to 10326
```

In my system, Termux API package and APK are not installed.
I've tried installing Termux API  app but installation failed.

### Steps to reproduce the behavior.

Behavior occurs sometimes. I've experienced it after system reboots.

### System information

* Termux application version: 0.117
* Android OS version: 11
* Device model: Redmi 8

### Stack trace
```
time: 1634525927735
msg: java.lang.SecurityException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7739)
	at com.android.server.notification.NotificationManagerService.isCallerInstantApp(NotificationManagerService.java:8752)
	at com.android.server.notification.NotificationManagerService.checkDisqualifyingFeatures(NotificationManagerService.java:6131)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5896)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5770)

stacktrace: java.lang.SecurityException: Package com.termux.api does not belong to 10326
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3207)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:581)
	at android.app.NotificationManager.notify(NotificationManager.java:531)
	at android.app.NotificationManager.notify(NotificationManager.java:507)
	at com.termux.app.TermuxService.updateNotification(TermuxService.java:780)
	at com.termux.app.TermuxService.createTermuxSession(TermuxService.java:550)
	at com.termux.app.TermuxService.createTermuxSession(TermuxService.java:505)
	at com.termux.app.terminal.TermuxTerminalSessionClient.addNewSession(TermuxTerminalSessionClient.java:327)
	at com.termux.app.TermuxActivity.lambda$onServiceConnected$1(TermuxActivity.java:362)
	at com.termux.app.TermuxActivity.lambda$onServiceConnected$1$TermuxActivity(Unknown Source:0)
	at com.termux.app.-$$Lambda$TermuxActivity$iAb3wbvCSw3C33cvEKUeEppeGmE.run(Unknown Source:2)
	at com.termux.app.TermuxInstaller.setupBootstrapIfNeeded(TermuxInstaller.java:79)
	at com.termux.app.TermuxActivity.onServiceConnected(TermuxActivity.java:354)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1978)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2010)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7739)
	at com.android.server.notification.NotificationManagerService.isCallerInstantApp(NotificationManagerService.java:8752)
	at com.android.server.notification.NotificationManagerService.checkDisqualifyingFeatures(NotificationManagerService.java:6131)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5896)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5770)
```

**Comment by Gryptonium** [comment]
Hey, I tried install termux from F-Droid and it keep saying "App not installed" what could be the problem. ![Screenshot_20211019-001541.png](https://user-images.githubusercontent.com/63162517/137823500-0d4e3ef3-9f96-4a96-9cb0-59ee74d8a82d.png)
