### ISSUE TITLE
[Bug]: app crash

### ISSUE THREAD

**Issue by why5684784** [termux/termux-app#2552]
### Problem description

`## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2022-01-30 01:36:04.374 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2022-01-30 01:20:13.577 UTC`  

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{533ae62 u0a187 TPSL idle procs:1 seq(0,0,0)}
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{533ae62 u0a187 TPSL idle procs:1 seq(0,0,0)}
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3082)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6821)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{533ae62 u0a187 TPSL idle procs:1 seq(0,0,0)}
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1587)
 at android.app.ContextImpl.startService(ContextImpl.java:1542)
 at android.content.ContextWrapper.startService(ContextWrapper.java:674)
 at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:242)
 at android.app.Activity.performCreate(Activity.java:7224)
 at android.app.Activity.performCreate(Activity.java:7213)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
 ... 11 more

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.4.153-perf+`  
**SDK_INT**: `28`  
**RELEASE**: `9`  
**ID**: `PKQ1.180904.001`  
**DISPLAY**: `PKQ1.180904.001`  
**INCREMENTAL**: `9.9.3`  
**SECURITY_PATCH**: `2019-09-05`  
**IS_DEBUGGABLE**: `1`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `xiaomi`  
**MODEL**: `Redmi Note 7`  
**PRODUCT**: `lavender`  
**BOARD**: `sdm660`  
**HARDWARE**: `qcom`  
**DEVICE**: `lavender`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##`

### Steps to reproduce the behavior.

runing some nodejs

### System information

* Termux application version:0.118
* Android OS version:android 9
* Device model:XiaoMi

**Comment by arbaleast** [comment]
## Report Info


**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2022-02-02 07:40:24.287 UTC`  
##

## Bootstrap Error

(150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".
TERMUX_FILES_DIR: `/data/data/com.termux/files`

## Termux Files Info


**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/data/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/data/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/data/com.termux/files: Permission denied
ls: /data/user/0/com.termux/files: Permission denied
ls: /data/user/0/com.termux/files: Permission denied
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: Permission denied
ls: /data/data/com.termux/files/usr: Permission denied
ls: /data/data/com.termux/files/home: Permission denied
ls: /data/data/com.termux/files/usr/bin/login: Permission denied
drwxrwx--x 545 system  system  u:object_r:system_data_file:s0                   36K 2022-01-31 15:49 /data/data
drwxrwxrwx   3 u0_a366 u0_a366 u:object_r:app_data_file:s0:c110,c257,c512,c768 4.0K 2022-02-01 15:05 /data/data/com.termux
lrwxrwxrwx   1 root    root    u:object_r:system_data_file:s0                    10 2017-11-06 09:12 /data/user/0 -> /data/data
drwxrwxrwx   3 u0_a366 u0_a366 u:object_r:app_data_file:s0:c110,c257,c512,c768 4.0K 2022-02-01 15:05 /data/user/0/com.termux

mount info:
147226 147163 259:10 / /data rw,nosuid,nodev,noatime master:36 - ext4 /dev/block/bootdevice/by-name/userdata rw,seclabel,noauto_da_alloc,resgid=1065,data=ordered

```
##


## Logcat Dump



````
$ /system/bin/logcat -d -t 3000 2>&1
--------- beginning of main
02-02 15:40:23.054 24573 24573 I com.termux: Late-enabling -Xcheck:jni
02-02 15:40:23.072 24573 24573 E com.termux: Unknown bits set in runtime_flags: 0x8000
02-02 15:40:23.085 24573 24573 V Riru    : jniRegisterNativeMethods com/android/internal/os/Zygote
02-02 15:40:23.085 24573 24573 I Riru    : replaced com.android.internal.os.Zygote#nativeForkAndSpecialize
02-02 15:40:23.086 24573 24573 V Riru    : jniRegisterNativeMethods com/android/internal/os/Zygote
02-02 15:40:23.086 24573 24573 I Riru    : replaced com.android.internal.os.Zygote#nativeSpecializeAppProcess
02-02 15:40:23.086 24573 24573 V Riru    : jniRegisterNativeMethods com/android/internal/os/Zygote
02-02 15:40:23.086 24573 24573 I Riru    : replaced com.android.internal.os.Zygote#nativeForkSystemServer
02-02 15:40:23.101 24573 24573 V Riru    : hook removed
02-02 15:40:23.101 24573 24573 V Riru    : storage_redirect: forkAndSpecializePost
02-02 15:40:23.101 24573 24573 V StorageRedirectInject: nativeForkAndSpecialize: package=com.termux, uid=10557
02-02 15:40:23.101 24573 24573 V StorageRedirectInject: install hook: package=com.termux, user=0
02-02 15:40:23.110 24573 24573 V StorageRedirectInject: install hook finished
02-02 15:40:23.110 24573 24573 V StorageRedirectInject: install hook: fix app interaction is disabled
02-02 15:40:23.187 24573 24573 I Typeface: Current DefaultTypeface ( default_roboto )
02-02 15:40:23.522 24573 24573 W com.termux: JIT profile information will not be recorded: profile file does not exits.
02-02 15:40:23.528 24573 24573 W ContextImpl: Failed to ensure /data/user/0/com.termux/cache: mkdir failed: EACCES (Permission denied)
02-02 15:40:23.528 24573 24573 W ContextImpl: Failed to update user.inode_cache: stat failed: EACCES (Permission denied)
02-02 15:40:23.529 24573 24573 W ContextImpl: Failed to ensure /data/user_de/0/com.termux/code_cache: mkdir failed: ENOENT (No such file or directory)
02-02 15:40:23.529 24573 24573 W ContextImpl: Failed to update user.inode_code_cache: stat failed: ENOENT (No such file or directory)
02-02 15:40:23.546 24573 24573 W ContextImpl: Failed to ensure /data/user/0/com.termux/shared_prefs: mkdir failed: EACCES (Permission denied)
02-02 15:40:23.546 24573 24573 I com.termux: Starting a blocking GC Alloc
02-02 15:40:23.546 24573 24573 I com.termux: Starting a blocking GC Alloc
02-02 15:40:23.592 24573 24573 W ContextImpl: Failed to ensure /data/user/0/com.termux/shared_prefs: mkdir failed: EACCES (Permission denied)
02-02 15:40:23.597 24573 24717 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files/home/crash_log.md": Failed to run Os.lstat() on file at path "/data/data/com.termux/files/home/crash_log.md": lstat failed: EACCES (Permission denied)
02-02 15:40:23.599 24573 24718 W ContextImpl: Failed to ensure /data/user/0/com.termux/cache: mkdir failed: EACCES (Permission denied)
02-02 15:40:23.600 24573 24718 W ContextImpl: Failed to update user.inode_cache: stat failed: EACCES (Permission denied)
02-02 15:40:23.600 24573 24718 E Termux  : Failed to get file type for file at path "/data/data/com.termux/cache/report_activity": Failed to run Os.lstat() on file at path "/data/data/com.termux/cache/report_activity": lstat failed: EACCES (Permission denied)
02-02 15:40:23.606 24573 24573 W Termux:SharedProperties: Not loading properties since file is null
02-02 15:40:23.632 24573 24573 D PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
02-02 15:40:23.657 24573 24710 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.termux/shared_prefs/com.termux_preferences.xml
02-02 15:40:23.682 24573 24573 W ContextImpl: Failed to ensure /data/user/0/com.termux/shared_prefs: mkdir failed: EACCES (Permission denied)
02-02 15:40:23.709 24573 24573 V SoundPool: SoundPool constructor: maxChannels=1, attr.usage=13, attr.flags=0x800, attr.tags=
02-02 15:40:23.710 24573 24573 V SoundPool: load: fd=63, offset=30509956, length=5090, priority=1
02-02 15:40:23.710 24573 24573 V SoundPool: create sampleID=1, fd=64, offset=5090 length=30509956
02-02 15:40:23.711 24573 24734 V SoundPool: Start decode
02-02 15:40:23.711 24573 24734 V SoundPool: fd 64, offset 30509956, size 5090
02-02 15:40:23.718 24573 24734 V LGCodecAdapter: convertMetaDataToMessage MetaDataBase
02-02 15:40:23.719 24573 24734 V LGCodecAdapter: load libLGCodecOSAL library
02-02 15:40:23.725 24573 24573 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
02-02 15:40:23.727 24573 24573 D BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
02-02 15:40:23.735 24573 24734 V LGCodecOSAL: Called LGCodeConvertMetaDataBaseToMessage
02-02 15:40:23.736 24573 24734 D MediaCodec: CreateByType mime=audio/vorbis
02-02 15:40:23.750 24573 24734 D MediaCodec: Mediacodec create pid=24573
02-02 15:40:23.751 24573 24734 D MediaCodec: init()++ name=c2.android.vorbis.decoder,nameIsType=1
02-02 15:40:23.770 24573 24738 D MediaCodec: kWhatInit received
02-02 15:40:23.771 24573 24738 D CCodec  : allocate(c2.android.vorbis.decoder)
02-02 15:40:23.778 24573 24738 I Codec2Client: Available Codec2 services: "software"
02-02 15:40:23.778 24573 24738 I Codec2Client: Creating a Codec2 client to service "software"
02-02 15:40:23.781 24573 24738 I Codec2Client: Client to Codec2 service "software" created
02-02 15:40:23.825 24573 24738 I CCodec  : Created component [c2.android.vorbis.decoder]
02-02 15:40:23.826 24573 24738 D CCodecConfig: read media type: audio/vorbis
02-02 15:40:23.829 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
02-02 15:40:23.830 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
02-02 15:40:23.830 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
02-02 15:40:23.830 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
02-02 15:40:23.830 24573 24711 I AdrenoGLES: QUALCOMM build                   : 080f0ce, I20154638fb
02-02 15:40:23.830 24573 24711 I AdrenoGLES: Build Date                       : 10/12/20
02-02 15:40:23.830 24573 24711 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.07
02-02 15:40:23.830 24573 24711 I AdrenoGLES: Local Branch                     : 
02-02 15:40:23.830 24573 24711 I AdrenoGLES: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.8.3.R1.10.00.00.520.073
02-02 15:40:23.830 24573 24711 I AdrenoGLES: Remote Branch                    : NONE
02-02 15:40:23.830 24573 24711 I AdrenoGLES: Reconstruct Branch               : NOTHING
02-02 15:40:23.830 24573 24711 I AdrenoGLES: Build Config                     : S P 8.0.12 AArch64
02-02 15:40:23.830 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
02-02 15:40:23.830 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
02-02 15:40:23.830 24573 24738 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
02-02 15:40:23.832 24573 24738 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
02-02 15:40:23.832 24573 24738 D CCodecConfig: c2 config is Dict {
02-02 15:40:23.832 24573 24738 D CCodecConfig:   c2::u32 coded.bitrate.value = 64000
02-02 15:40:23.832 24573 24738 D CCodecConfig:   c2::u32 input.buffers.max-size.value = 32768
02-02 15:40:23.832 24573 24738 D CCodecConfig:   c2::u32 input.delay.value = 0
02-02 15:40:23.832 24573 24738 D CCodecConfig:   string input.media-type.value = "audio/vorbis"
02-02 15:40:23.832 24573 24738 D CCodecConfig:   string output.media-type.value = "audio/raw"
02-02 15:40:23.832 24573 24738 D CCodecConfig:   c2::u32 raw.channel-count.value = 1
02-02 15:40:23.832 24573 24738 D CCodecConfig:   c2::u32 raw.sample-rate.value = 48000
02-02 15:40:23.832 24573 24738 D CCodecConfig: }
02-02 15:40:23.833 24573 24738 D MediaCodec: onComponentAllocated() componentName=c2.android.vorbis.decoder
02-02 15:40:23.833 24573 24738 D MediaCodec: kWhatComponentAllocated received
02-02 15:40:23.833 24573 24734 D MediaCodec: init()--
02-02 15:40:23.833 24573 24738 D MediaCodec: kWhatConfigure received
02-02 15:40:23.833 24573 24738 V LGCodecAdapter: called getLGCodecSpecificData
02-02 15:40:23.833 24573 24738 V LGCodecOSAL: Called LGgetCodecSpecificDataMSG
02-02 15:40:23.834 24573 24738 D CCodecConfig: no c2 equivalents for durationUs
02-02 15:40:23.834 24573 24738 D CCodecConfig: no c2 equivalents for csd-1
02-02 15:40:23.834 24573 24738 D CCodecConfig: no c2 equivalents for track-id
02-02 15:40:23.834 24573 24738 D CCodecConfig: no c2 equivalents for channel-mask
02-02 15:40:23.834 24573 24738 D CCodecConfig: no c2 equivalents for real-sample-rate
02-02 15:40:23.834 24573 24738 D CCodecConfig: no c2 equivalents for real-sample-bits
02-02 15:40:23.834 24573 24738 D CCodecConfig: c2 config is Dict {
02-02 15:40:23.834 24573 24738 D CCodecConfig:   c2::u32 coded.bitrate.value = 64000
02-02 15:40:23.834 24573 24738 D CCodecConfig:   c2::u32 input.buffers.max-size.value = 32768
02-02 15:40:23.834 24573 24738 D CCodecConfig:   c2::u32 input.delay.value = 0
02-02 15:40:23.834 24573 24738 D CCodecConfig:   string input.media-type.value = "audio/vorbis"
02-02 15:40:23.834 24573 24738 D CCodecConfig:   string output.media-type.value = "audio/raw"
02-02 15:40:23.834 24573 24738 D CCodecConfig:   c2::u32 raw.channel-count.value = 1
02-02 15:40:23.834 24573 24738 D CCodecConfig:   c2::u32 raw.sample-rate.value = 44100
02-02 15:40:23.834 24573 24738 D CCodecConfig: }
02-02 15:40:23.834 24573 24738 W Codec2Client: query -- param skipped: index = 1107298332.
02-02 15:40:23.834 24573 24738 D CCodec  : setup formats input: AMessage(what = 0x00000000) = {
02-02 15:40:23.834 24573 24738 D CCodec  :   int32_t channel-count = 1
02-02 15:40:23.834 24573 24738 D CCodec  :   int32_t max-input-size = 32768
02-02 15:40:23.834 24573 24738 D CCodec  :   string mime = "audio/vorbis"
02-02 15:40:23.834 24573 24738 D CCodec  :   int32_t sample-rate = 44100
02-02 15:40:23.834 24573 24738 D CCodec  : } and output: AMessage(what = 0x00000000) = {
02-02 15:40:23.834 24573 24738 D CCodec  :   int32_t channel-count = 1
02-02 15:40:23.834 24573 24738 D CCodec  :   string mime = "audio/raw"
02-02 15:40:23.834 24573 24738 D CCodec  :   int32_t sample-rate = 44100
02-02 15:40:23.834 24573 24738 D CCodec  :   int32_t channel-mask = 1
02-02 15:40:23.834 24573 24738 D CCodec  : }
02-02 15:40:23.834 24573 24738 D MediaCodec: onComponentConfigured()
02-02 15:40:23.834 24573 24738 D MediaCodec: kWhatComponentConfigured received
02-02 15:40:23.835 24573 24734 D MediaCodec: start()
02-02 15:40:23.835 24573 24738 D MediaCodec: kWhatStart received
02-02 15:40:23.836 24573 24711 I AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
02-02 15:40:23.838 24573 24738 W Codec2Client: query -- param skipped: index = 1342179345.
02-02 15:40:23.838 24573 24738 W Codec2Client: query -- param skipped: index = 2415921170.
02-02 15:40:23.842 24573 24738 D CCodecBufferChannel: [c2.android.vorbis.decoder#669] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
02-02 15:40:23.845 24573 24738 I CCodecBufferChannel: [c2.android.vorbis.decoder#669] Created output block pool with allocatorID 16 => poolID 48 - OK
02-02 15:40:23.846 24573 24738 D CCodecBufferChannel: [c2.android.vorbis.decoder#669] Configured output block pool ids 48 => OK
02-02 15:40:23.846 24573 24738 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-02 15:40:23.865 24573 24734 D MediaCodec: stop()
02-02 15:40:23.865 24573 24738 D MediaCodec: kWhatStop or kWhatRelease received targetState=2 and mState=6
02-02 15:40:23.866 24573 24738 D MediaCodec: kWhatStopCompleted received
02-02 15:40:23.866 24573 24734 D MediaCodec: release()
02-02 15:40:23.866 24573 24738 D MediaCodec: kWhatStop or kWhatRelease received targetState=0 and mState=2
02-02 15:40:23.866 24573 24768 D MediaCodec: onReleaseCompleted()
02-02 15:40:23.866 24573 24738 D MediaCodec: kWhatReleaseCompleted received
02-02 15:40:23.869 24573 24734 D MediaCodec: ~MediaCodec()
02-02 15:40:23.870 24573 24734 V SoundPool: close(64)
02-02 15:40:23.870 24573 24734 V SoundPool: pointer = 0x7b7bd61000, size = 10306, sampleRate = 44100, numChannels = 1
02-02 15:40:23.902 24573 24711 W Gralloc3: mapper 3.x is not supported
02-02 15:40:24.001 24573 24573 W ContextImpl: Failed to ensure /data/user/0/com.termux/files: mkdir failed: EACCES (Permission denied)
02-02 15:40:24.001 24573 24573 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files": Failed to run Os.stat() on file at path "/data/data/com.termux/files": stat failed: EACCES (Permission denied)
02-02 15:40:24.004 24573 24573 E Termux:TermuxInstaller: (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".
02-02 15:40:24.004 24573 24573 E Termux:TermuxInstaller: TERMUX_FILES_DIR: `/data/data/com.termux/files`
02-02 15:40:24.005 24573 24573 W ContextImpl: Failed to ensure /data/user/0/com.termux/files: mkdir failed: EACCES (Permission denied)
02-02 15:40:24.018 24573 24573 W com.termux: Accessing hidden field Ljava/lang/UNIXProcess;->pid:I (greylist, reflection, allowed)

````
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**TERMUX_FILES_DIR**: `/data/data/com.termux/files`  
**IS_TERMUX_FILES_DIR_ACCESSIBLE**: `false - (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Device Info

### Software

**OS_VERSION**: `4.9.193-perf`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `QKQ1.191222.002`  
**DISPLAY**: `QKQ1.191222.002`  
**INCREMENTAL**: `2102515440279.OPEN_KR`  
**SECURITY_PATCH**: `2021-01-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `LGE`  
**BRAND**: `lge`  
**MODEL**: `LM-V350N`  
**PRODUCT**: `judyp_lao_com`  
**BOARD**: `sdm845`  
**HARDWARE**: `judyp`  
**DEVICE**: `judyp`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by arbaleast** [comment]
permission deny？ why？it already get storage permission.

**Comment by 2096779623** [comment]
> 权限拒绝？为什么？它已经获得了存储权限

Try reinstall Termux And give the storage permission.

**Comment by arbaleast** [comment]
> > 权限拒绝？为什么？它已经获得了存储权限
> 
> Try reinstall Termux And give the storage permission.

thank you

**Comment by agnostic-apollo** [comment]
Apps don't need storage permission to access their `/data/data/<package_name>` directories.

@arbaleast your crash is not related to original poster's crash, which I'll look into solving by catching the exception. You should have opened a separate issue for your crash. Anyhow, considering that `/data/data/com.termux` exists, but you are getting permission denied for `/data/data/com.termux/files`, it likely means you have messed around with ownership/permissions. Are you rooted?

If yes, then either uninstall and reinstall the app completely, or check https://github.com/termux/termux-app/issues/2080#issuecomment-846575028 and manually fix ownership/permissions.

```
ls: /data/data/com.termux/files: Permission denied
drwxrwxrwx   3 u0_a366 u0_a366 u:object_r:app_data_file:s0:c110,c257,c512,c768 4.0K 2022-02-01 15:05 /data/data/com.termux
lrwxrwxrwx   1 root    root    u:object_r:system_data_file:s0                    10 2017-11-06 09:12 /data/user/0 -> /data/data
drwxrwxrwx   3 u0_a366 u0_a366 u:object_r:app_data_file:s0:c110,c257,c512,c768 4.0K 2022-02-01 15:05 /data/user/0/com.termux
```

**Comment by arbaleast** [comment]
yes，I ’m rooted. It seem that some immutable file remained. after delete these file，everything work right. thank you for reply.

**Comment by agnostic-apollo** [comment]
Welcome. All that debug info added in `v0.118.0` is proving useful.

**Comment by why5684784** [comment]
> Welcome. All that debug info added in `v0.118.0` is proving useful.
Can you fix the bug information I submitted? This error persists from 0.117 to 0.118.

**Comment by agnostic-apollo** [comment]
>Can you fix the bug information I submitted?

You can fix it yourself by disabling battery optimizations for termux app. I'll look into not crashing the app and exiting it, but that's all I can do, when exception is thrown, `TermuxService` will not start due to Android background restrictions and you will have to start termux again yourself.

**Comment by why5684784** [comment]
> > Can you fix the bug information I submitted?
> 
> You can fix it yourself by disabling battery optimizations for termux app. I'll look into not crashing the app and exiting it, but that's all I can do, when exception is thrown, `TermuxService` will not start due to Android background restrictions and you will have to start termux again yourself.

Battery optimization has been disabled. I don't think this problem is caused by battery optimization. I guess it should be caused by multithreading concurrent asynchronous writing to files.

**Comment by agnostic-apollo** [comment]
> `RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{533ae62 u0a187 TPSL idle procs:1 seq(0,0,0)}
l`

https://developer.android.com/about/versions/oreo/background#services
