### ISSUE TITLE
[Bug]: Cannot work with RUBY ON RAILS for missing library "libssl.so.1.1"

### ISSUE THREAD

**Issue by ajpalok** [termux/termux-app#2665]
### Problem description

While working with Ruby on rails in Termux I have been encountered with the issue of missing library 
 `libssl.so.1.1` and because of some personal issues, I had to close the work for a long time. Before that, I learned many people got the same issue with there projects from different languages and discussed there issues in [Termux Community](https://www.reddit.com/r/termux/) and adviced us to update our repos. But I got the same issues even after upgrading app and repos. [Their suggestions](https://www.reddit.com/r/termux/comments/t3fvf8/comment/hz1oaq1/) was for that me.

The error I got recently (18 minutes ago after updating the packages again) was:
```sh
~ cd /storage/sdcard/webdev/ && rails s
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require': dlopen failed: library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/puma_http11.so in namespace (default) - /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/puma_http11.so (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma.rb:13:in `<main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.4/lib/bundler.rb:176:in `require'
        from /storage/sdcard/webdev/config/application.rb:7:in `<main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/commands/server/server_command.rb:138:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/commands/server/server_command.rb:135:in `perform'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/base.rb:69:in `perform'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command.rb:48:in `invoke'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/commands.rb:18:in `<main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /storage/sdcard/webdev/bin/rails:5:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /storage/sdcard/webdev/bin/spring:10:in `block in <top (required)>'
        from <internal:kernel>:90:in `tap'
        from /storage/sdcard/webdev/bin/spring:7:in `<top (required)>'
        from bin/rails:2:in `load'
        from bin/rails:2:in `<main>'
```

### Steps to reproduce the behavior.

`rails s`

### What is the expected behavior?

Will open a webserver from the Rails project

### System information

* Termux application version: 118
* Android OS version: 11
* Device model: Nokia 2.2

**Comment by Grimler91** [comment]
Probably you need to reinstall the gems that are linked against openssl. Puma is not linked against openssl-1.1 when I installed it just now: 

```
$ ldd $PREFIX/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/puma_http11.so
libandroid-support.so
libruby.so.3.1
libssl.so.3
libcrypto.so.3
libc.so
```

`export LD_LIBRARY_PATH=$PREFIX/lib/openssl-1.1` might work as a workaround as well.

**Comment by ajpalok** [comment]
Thanks for the help, Reinstalling `Puma` fixed everything
