### ISSUE TITLE
[Bug]:  Termux-storage-setup Crash

### ISSUE THREAD

**Issue by Duvio** [termux/termux-app#2703]
### Problem description

When you had already run termux-setup-storag once, removed the execute bit from the storage/ folder, and run termux-setup-storage again, it results in a termux crash report. This is because on linux you can only access folders when their execute bit is set. If you remove the execute bit from a folder using chmod, you can for example not cd into it anymore.

## Report Info

**User Action**: `crash report`  
**Sender**: `termux-storage`  
**Report Timestamp**: `2022-04-11 01:00:49.773 UTC`  
##

## Setup Storage Error

**Error Code**: `302`  
**Error Message (FileUtils Error)**:
```
Clearing ~/storage directory at path "/data/data/com.termux/files/home/storage" failed.
Exception: /data/data/com.termux/files/home/storage: failed to delete one or more files; see suppressed exceptions for details
```

### StackTraces

```
java.nio.file.FileSystemException: /data/data/com.termux/files/home/storage: failed to delete one or more files; see suppressed exceptions for details
	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:828)
	at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:642)
	at com.termux.shared.file.FileUtils.clearDirectory(FileUtils.java:1269)
	at com.termux.app.TermuxInstaller$2.run(TermuxInstaller.java:272)
	Suppressed: java.nio.file.AccessDeniedException: shared
		at sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:391)
		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:374)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:655)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:685)
		at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:628)
		... 2 more
	Suppressed: java.nio.file.AccessDeniedException: downloads
		at sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:391)
		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:374)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:655)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:685)
		at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:628)
		... 2 more
	Suppressed: java.nio.file.AccessDeniedException: dcim
		at sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:391)
		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:374)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:655)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:685)
		at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:628)
		... 2 more
	Suppressed: java.nio.file.AccessDeniedException: pictures
		at sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:391)
		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:374)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:655)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:685)
		at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:628)
		... 2 more
	Suppressed: java.nio.file.AccessDeniedException: music
		at sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:391)
		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:374)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:655)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:685)
		at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:628)
		... 2 more
	Suppressed: java.nio.file.AccessDeniedException: movies
		at sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:391)
		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:374)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:655)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:685)
		at com.google.common.io.MoreFiles.deleteDirectoryContents(MoreFiles.java:628)
		... 2 more

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `5.4.86-qgki-23158112-abA528BXXU1BUL7`  
**SDK_INT**: `31`  
**RELEASE**: `12`  
**ID**: `SP1A.210812.016`  
**DISPLAY**: `SP1A.210812.016.A528BXXU1BUL7`  
**INCREMENTAL**: `A528BXXU1BUL7`  
**SECURITY_PATCH**: `2022-01-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-A528B`  
**PRODUCT**: `a52sxqeea`  
**BOARD**: `lahaina`  
**HARDWARE**: `qcom`  
**DEVICE**: `a52sxq`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

termux-setup-storage
chmod -x storage
termux-setup-storage

### What is the expected behavior?

Expected: Do what it is supposed to do and exit fine

Reality: Does what it is supposed to do but leaves a notification with a termux crash report behind

### System information

Written down above

**Comment by agnostic-apollo** [comment]
This would indeed be an issue. Will look into fixing it in future.

**Comment by misipost** [comment]
Try this:
Connecting Termux to external sd card :
copy my code to "linksd.txt", and run : sh linksd.txt

#code start --
echo "detecting microSD name"
ls ~/../../../../../storage > storage.txt;
sed -i -n '/-/p' storage.txt;
file="storage.txt"
xsd=$(cat "$file")

DIR=~/../../../../../storage/$xsd/termuxsd
if [ -d "$DIR" ]; then
    echo "termuxsd exists."
else
    echo "Creating Dir"
    mkdir ~/../../../../../storage/$xsd/termuxsd
fi

LINK=~/../../../../../data/data/com.termux/files/home/storage/termuxsd
if [ -h "$LINK" ]; then
    echo "LINK exists."
else
    echo "Creating Link"
    ln -s ~/../../../../../storage/$xsd/termuxsd ~/../../../../../data/data/com.termux/files/home/storage/termuxsd
fi
FILE=~/storage/termuxsd/FileOnExtSdCard.txt
if [ -f "$FILE" ]; then
    echo "1.st FILE exists."
else
    echo "Creating 1.st File"
    echo "FileOnExtSdCard" > ~/storage/termuxsd/FileOnExtSdCard.txt
fi
rm storage.txt ;
cd ~/storage/termuxsd && ls 

echo "🇪‌🇽‌🇹‌🇪‌🇷‌🇳‌🇦‌🇱‌ 🇸‌🇩‌ 🇼‌🇦‌🇸‌ 🇱‌🇮‌🇳‌🇰‌🇪‌🇩‌ 🇹‌🇴‌ 🇹‌🇪‌🇷‌🇲‌🇺‌🇽‌"
echo "For External Sd Folder :"
echo "type in : "
echo "cd ~/storage/termuxsd"
#code end--

enjoy :)
