### ISSUE TITLE
[Bug]: Can not install

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-app#2753]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2022-05-01 11:27:06.256 UTC`  
##

## Bootstrap Error

**Error Code**: `301`  
**Error Message (FileUtils Error)**:
```
Deleting termux prefix directory file at path "/data/data/com.termux/files/usr" failed.
Exception: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
```

### StackTraces

```
java.nio.file.FileSystemException: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:828)
	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:587)
	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1195)
	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1115)
	at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:126)
	Suppressed: java.nio.file.AccessDeniedException: usr
		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:141)
		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:45)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:656)
		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:570)
		... 3 more

```
##

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/data/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/data/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: No such file or directory
ls: /data/data/com.termux/files/usr/bin/login: Permission denied
drwxrwx--x 243 system  system  u:object_r:system_data_file:s0                   24K 2022-05-01 16:54 /data/data
drwx------   5 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 18:32 /data/data/com.termux
drwxrwx--x   4 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 18:32 /data/data/com.termux/files
d---------   4 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 19:25 /data/data/com.termux/files/home
d---------  11 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 18:32 /data/data/com.termux/files/usr
lrwxrwxrwx   1 root    root    u:object_r:system_data_file:s0                    10 2022-03-03 12:16 /data/user/0 -> /data/data
drwx------   5 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 18:32 /data/user/0/com.termux
drwxrwx--x   4 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 18:32 /data/user/0/com.termux/files
drwxrwx--x   4 u0_a250 u0_a250 u:object_r:app_data_file:s0:c250,c256,c512,c768 3.4K 2022-05-01 18:32 /data/user/0/com.termux/files

mount info:
7406 7339 259:53 / /data rw,nosuid,nodev,noatime master:37 - f2fs /dev/block/by-name/userdata rw,seclabel,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,extent_cache,mode=adaptive,inline_encrypt,sdp_encrypt,active_logs=6,alloc_mode=default,fsync_mode=posix

```
##

## Logcat Dump

``````
$ /system/bin/logcat -d -t 3000 2>&1
--------- beginning of system
05-01 17:32:15.694 16590 16610 E HwActivityThreadImpl: connect Error.
05-01 17:37:28.597 19823 19842 E HwActivityThreadImpl: connect Error.
05-01 17:37:33.865 19976 19997 E HwActivityThreadImpl: connect Error.
05-01 17:38:14.181 20904 20924 E HwActivityThreadImpl: connect Error.
--------- beginning of main
05-01 19:25:39.859 25773 16665 E libc    : Access denied finding property "ro.kirin.product.platform"
05-01 19:25:43.861 25773 16688 E libc    : Access denied finding property "ro.kirin.product.platform"
05-01 19:26:03.511 25773 25773 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files/usr/tmp": Failed to run Os.lstat() on file at path "/data/data/com.termux/files/usr/tmp": lstat failed: EACCES (Permission denied)
05-01 19:26:04.314 25773 16769 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files/home/crash_log.md": Failed to run Os.lstat() on file at path "/data/data/com.termux/files/home/crash_log.md": lstat failed: EACCES (Permission denied)
05-01 19:26:04.367 25773 16774 E libc    : Access denied finding property "ro.kirin.product.platform"
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: Bootstrap Error:
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: **Error Code**: `301`  
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: **Error Message (FileUtils Error)**:
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: ```
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: Deleting termux prefix directory file at path "/data/data/com.termux/files/usr" failed.
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: Exception: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: ```
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: ### StackTraces
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: ```
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: java.nio.file.FileSystemException: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:828)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:587)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1195)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1115)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 	at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:126)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 	Suppressed: java.nio.file.AccessDeniedException: usr
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:141)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:45)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:656)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:570)
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 		... 3 more
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: 
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: ```
05-01 19:26:04.534 25773 16798 E Termux:TermuxInstaller: ##
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: Bootstrap Error:
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: **Error Code**: `301`  
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: **Error Message (FileUtils Error)**:
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: ```
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: Deleting termux prefix directory file at path "/data/data/com.termux/files/usr" failed.
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: Exception: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: ```
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: ### StackTraces
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: ```
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: java.nio.file.FileSystemException: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:828)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:587)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1195)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1115)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 	at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:126)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 	Suppressed: java.nio.file.AccessDeniedException: usr
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:141)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:45)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:656)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:570)
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 		... 3 more
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: 
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: ```
05-01 19:26:06.191 25773 16824 E Termux:TermuxInstaller: ##
05-01 19:26:09.648 25773 25773 E HwViewGroupImpl: parse speed value length error
05-01 19:27:06.014 25773 19305 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files/home/crash_log.md": Failed to run Os.lstat() on file at path "/data/data/com.termux/files/home/crash_log.md": lstat failed: EACCES (Permission denied)
05-01 19:27:06.066 25773 19310 E libc    : Access denied finding property "ro.kirin.product.platform"
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: Bootstrap Error:
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: **Error Code**: `301`  
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: **Error Message (FileUtils Error)**:
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: ```
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: Deleting termux prefix directory file at path "/data/data/com.termux/files/usr" failed.
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: Exception: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: ```
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: ### StackTraces
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: ```
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: java.nio.file.FileSystemException: /data/data/com.termux/files/usr: failed to delete one or more files; see suppressed exceptions for details
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:828)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:587)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1195)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1115)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 	at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:126)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 	Suppressed: java.nio.file.AccessDeniedException: usr
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:141)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 		at sun.nio.fs.UnixSecureDirectoryStream.newDirectoryStream(UnixSecureDirectoryStream.java:45)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:656)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:570)
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 		... 3 more
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: 
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: ```
05-01 19:27:06.130 25773 19334 E Termux:TermuxInstaller: ##

``````
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.14.116`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `HUAWEIVCE-AL00`  
**DISPLAY**: `VCE-AL00 10.0.0.166(C00E34R2P4)`  
**INCREMENTAL**: `10.0.0.166C00`  
**SECURITY_PATCH**: `2020-08-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HUAWEI`  
**MODEL**: `VCE-AL00`  
**PRODUCT**: `VCE-AL00`  
**BOARD**: `VCE`  
**HARDWARE**: `kirin970`  
**DEVICE**: `HWVCE`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

1.Download Termux form Github Releases  

2.Install then open the Termux

### System information

* Termux application version:0.118.0
* Android OS version:10
* Device model:HUAWEI VCE-AL00

**Comment by agnostic-apollo** [comment]
Is this from a fresh installation or did you restore some backup or something?

Send output of `cat /proc/self/status` from failsafe session.

https://wiki.termux.com/wiki/Recover_a_broken_environment

**Comment by 2096779623** [comment]
> Is this from a fresh installation or did you restore some backup or something?
> 
> Send output of `cat /proc/$TERMUX_APP_PID/status` from failsafe session.
> 
> https://wiki.termux.com/wiki/Recover_a_broken_environment

Permission issue, fixed.

**Comment by jcsdev31** [comment]
> > Is this from a fresh installation or did you restore some backup or something?
> > Send output of `cat /proc/$TERMUX_APP_PID/status` from failsafe session.
> > https://wiki.termux.com/wiki/Recover_a_broken_environment
> 
> Permission issue, fixed.
How did you fix this? I am having the same issue
