### ISSUE TITLE
[Feature]: add timestamps to crash report filename.

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-app#2850]
### Feature description

I have had 3 crashes last week. Termux creates a `termux-crash_report.log` in internal storage but every new crashes overwrites and writes the last crash log.  So I had like to have all the reports if each crash for later submission.

### Additional information

And I don't fully understand how it works I had a crash few minutes ago and here is what I found in `/sdcard` 

 ❯ cat *.log
## Report Info

**User Action**: `crash report`
**Sender**: `TermuxActivity`
**Report Timestamp**: `2022-06-12 20:24:22.468 UTC`
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`
**Crash Timestamp**: `2022-06-12 20:24:16.363 UTC`

**Crash Message**:
```
OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

### Stacktrace

```
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

```
##

## Termux App Info

**APP_NAME**: `Termux`
**PACKAGE_NAME**: `com.termux`
**VERSION_NAME**: `0.118.0`
**VERSION_CODE**: `118`
**TARGET_SDK**: `28`
**IS_DEBUGGABLE_BUILD**: `false`
**APK_RELEASE**: `F-Droid`
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`
##

### Software

**OS_VERSION**: `4.4.146`
**SDK_INT**: `28`
**RELEASE**: `9`
**HARDWARE**: `mt6757`
**SECURITY_PATCH**: `2020-08-05`
**IS_DEBUGGABLE**: `0`
**IS_TREBLE_ENABLED**: `true`
**TYPE**: `user`
**TAGS**: `release-keys`
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`
##%
(I removed  some info like device manufacturer)

And here is what I found in `$HOME` directory:

❯ cat crash_log_backup.md
## Crash Details

**Crash Thread**: `Thread[main,5,main]`
**Crash Timestamp**: `2022-06-20 11:10:48.140 UTC`

**Crash Message**:
```
Failed to allocate a 552 byte allocation with 57296 free bytes and 55KB until OOM, max allowed footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 0 bytes)
```

### Stacktrace

```
java.lang.OutOfMemoryError: Failed to allocate a 552 byte allocation with 57296 free bytes and 55KB until OOM, max allowed footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 0 bytes)
        at com.termux.terminal.TerminalRow.<init>(TerminalRow.java:30)
        at com.termux.terminal.TerminalBuffer.resize(TerminalBuffer.java:235)
        at com.termux.terminal.TerminalEmulator.resizeScreen(TerminalEmulator.java:397)
        at com.termux.terminal.TerminalEmulator.resize(TerminalEmulator.java:391)
        at com.termux.terminal.TerminalSession.updateSize(TerminalSession.java:108)
        at com.termux.view.TerminalView.updateSize(TerminalView.java:896)
        at com.termux.view.TerminalView.setTextSize(TerminalView.java:450)
        at com.termux.app.terminal.TermuxTerminalViewClient.changeFontSize(TermuxTerminalViewClient.java:490)
        at com.termux.app.terminal.TermuxTerminalViewClient.onScale(TermuxTerminalViewClient.java:167)
        at com.termux.view.TerminalView$1.onScale(TerminalView.java:144)
        at com.termux.view.GestureAndScaleRecognizer$3.onScale(GestureAndScaleRecognizer.java:85)
        at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:372)
        at com.termux.view.GestureAndScaleRecognizer.onTouchEvent(GestureAndScaleRecognizer.java:93)
        at com.termux.view.TerminalView.onTouchEvent(TerminalView.java:572)
        at android.view.View.dispatchTouchEvent(View.java:12545)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3084)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3084)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3084)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3084)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3084)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3084)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:441)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
        at android.view.View.dispatchPointerEvent(View.java:12789)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5280)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5074)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4587)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4640)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4606)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4746)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4614)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4803)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4587)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4640)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4606)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4614)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4587)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7337)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7306)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7263)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7454)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7421)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7477)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:953)
        at android.view.Choreographer.doCallbacks(Choreographer.java:765)
        at android.view.Choreographer.doFrame(Choreographer.java:691)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:939)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```
##

## Termux App Info

**APP_NAME**: `Termux`
**PACKAGE_NAME**: `com.termux`
**VERSION_NAME**: `0.118.0`
**VERSION_CODE**: `118`
**TARGET_SDK**: `28`
**IS_DEBUGGABLE_BUILD**: `false`
**APK_RELEASE**: `F-Droid`
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`
##

### Software

**OS_VERSION**: `4.4.146`
**SDK_INT**: `28`
**RELEASE**: `9`

**SECURITY_PATCH**: `2020-08-05`
**IS_DEBUGGABLE**: `0`
**IS_TREBLE_ENABLED**: `true`
**TYPE**: `user`
**TAGS**: `release-keys`

### Hardware

**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`
##

Look at the dates.

**Comment by JARMSBRO** [comment]
H
