### ISSUE TITLE
Report Text

### ISSUE THREAD

**Issue by purwahire** [termux/termux-app#2886]
## Transcript

```
sh: /system/etc/mkshrc[9]: getprop: not found
android:/ $
```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**IS_INSTALLED_ON_EXTERNAL_STORAGE**: `true`  
**FILES_DIR**: `/mnt/expand/5339f040-2a8f-4b1e-9c13-ed88e99cd669/user/0/com.termux/files`  
**TERMUX_FILES_DIR**: `/data/data/com.termux/files`  
**IS_TERMUX_FILES_DIR_ACCESSIBLE**: `false - (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `3.10.49`  
**SDK_INT**: `25`  
**RELEASE**: `7.1.1`  
**ID**: `NMF26F`  
**DISPLAY**: `00WW_0_68R`  
**INCREMENTAL**: `00WW_0_68R`  
**SECURITY_PATCH**: `2019-11-01`  
**IS_DEBUGGABLE**: `0`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HMD Global`  
**BRAND**: `Nokia`  
**MODEL**: `Nokia 2`  
**PRODUCT**: `Dynamo_00WW`  
**BOARD**: `MSM8909`  
**HARDWARE**: `qcom`  
**DEVICE**: `E1M`  
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  
##

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/mnt/expand/5339f040-2a8f-4b1e-9c13-ed88e99cd669/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/mnt/expand/5339f040-2a8f-4b1e-9c13-ed88e99cd669/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/data/com.termux: No such file or directory
ls: /data/user/0/com.termux: No such file or directory
ls: /data/data/com.termux/files: No such file or directory
ls: /data/user/0/com.termux/files: No such file or directory
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: No such file or directory
ls: /data/data/com.termux/files/usr: No such file or directory
ls: /data/data/com.termux/files/home: No such file or directory
ls: /data/data/com.termux/files/usr/bin/login: No such file or directory
drwxrwx--x 208 system  system  u:object_r:system_data_file:s0         12K 2022-07-13 23:28 /data/data
lrwxrwxrwx   1 root    root    u:object_r:system_data_file:s0          10 1970-02-04 09:03 /data/user/0 -> /data/data
drwxrwx--x   2 u0_a145 u0_a145 u:object_r:app_data_file:s0:c512,c768 4.0K 2022-07-14 00:34 /mnt/expand/5339f040-2a8f-4b1e-9c13-ed88e99cd669/user/0/com.termux/files

mount info:
984 936 259:15 / /data rw,nosuid,nodev,relatime master:15 - ext4 /dev/block/bootdevice/by-name/userdata rw,seclabel,discard,noauto_da_alloc,data=ordered

```
##

## Logcat Dump

``````
$ /system/bin/logcat -d -t 3000 2>&1
--------- beginning of main
07-14 00:55:27.265  3967  3967 W Termux:SharedProperties: Not loading properties since file is null
07-14 00:55:27.357  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@fc522ff
07-14 00:55:27.357  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@7d3c8cc
07-14 00:55:27.357  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@622d715
07-14 00:55:27.357  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@99c2a2a
07-14 00:55:27.368  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2d2f01b
07-14 00:55:27.392  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8daa5b8
07-14 00:55:27.575  3967 12322 I OMXClient: MuxOMX ctor
07-14 00:55:29.891  3967  3967 D HyperClipMenu: createMenuItem: mode=com.android.internal.view.FloatingActionMode@d06e18e
07-14 00:55:29.891  3967  3967 D HyperClipMenu: initializeHyperClipMenu:
07-14 00:55:29.898  3967  3967 D HyperClipMenu: initializeHyperClipMenu: hyperclipId=null
07-14 00:55:29.900  3967  3967 E HyperClipMenu: HyperClip is not installed.
07-14 00:55:29.902  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:29.902  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:29.903  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:29.903  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:30.118  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:30.118  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:30.118  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:55:30.118  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:56:05.855  3967  3967 D HyperClipMenu: createMenuItem: mode=com.android.internal.view.FloatingActionMode@3505f5a
07-14 00:56:05.855  3967  3967 D HyperClipMenu: initializeHyperClipMenu:
07-14 00:56:05.861  3967  3967 D HyperClipMenu: initializeHyperClipMenu: hyperclipId=null
07-14 00:56:05.862  3967  3967 E HyperClipMenu: HyperClip is not installed.
07-14 00:56:06.092  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:56:06.092  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:56:06.092  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:56:06.093  3967  3967 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
07-14 00:56:08.860  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@796b736
07-14 00:56:08.860  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@c2a637
07-14 00:56:08.864  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b8f10c2
07-14 00:56:08.864  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b116ed3
07-14 00:56:13.353  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b618708
07-14 00:56:13.353  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@7db1ea1
07-14 00:56:13.390  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@7411d4c
07-14 00:56:13.390  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@26ed195
07-14 00:56:13.396  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@708c238
07-14 00:56:13.396  3967  3967 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@937f211
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: (1) APT Info Command:
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Previous State: `Executing`
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Current State: `Failed`
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Stdout: -
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Stderr: -
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Exit Code: -
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Error Code: `2`
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Error Message:
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: ```
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Failed to execute "(1) APT Info Command" termux task command
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: ```
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: StackTraces:
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: ```
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: java.io.IOException: Cannot run program "/data/data/com.termux/files/usr/bin/bash" (in directory "/data/data/com.termux/files/home"): error=2, No such file or directory
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at java.lang.Runtime.exec(Runtime.java:691)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at com.termux.shared.shell.TermuxTask.execute(TermuxTask.java:96)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at com.termux.shared.termux.TermuxUtils.geAPTInfoMarkdownString(TermuxUtils.java:430)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at com.termux.app.terminal.TermuxTerminalViewClient$2.run(TermuxTerminalViewClient.java:730)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: Caused by: java.io.IOException: error=2, No such file or directory
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at java.lang.ProcessImpl.start(ProcessImpl.java:128)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 	... 4 more
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: 
07-14 00:56:17.310  3967 12453 E Termux:TermuxUtils: ```

``````
##

**Comment by agnostic-apollo** [comment]
Do not install termux on external sd card.
