### ISSUE TITLE
Can't start or uninstall termux

### ISSUE THREAD

**Issue by stalek71** [termux/termux-app#3099]
### Problem description

I tried to start termux, but it crashes. I can't reinstall it because installer says it is not installed  while it is available. I have no link to it as it's not visible on all apps, but fdroid shows it's installed and tries to run it.

### Steps to reproduce the behavior.

Just run

### What is the expected behavior?

Not crashing

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2022-11-17 22:20:16.771 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2022-11-17 22:16:40.806 UTC`  

**Crash Message**:
```
Bad notification(tag=null, id=1337) posted from package com.termux, crashing app(uid=10454, pid=28846): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.termux id=0x7f070072) visible user=0 )
```

### Stacktrace

```
android.app.RemoteServiceException: Bad notification(tag=null, id=1337) posted from package com.termux, crashing app(uid=10454, pid=28846): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.termux id=0x7f070072) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.14.190-perf+`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `RKQ1.201022.002`  
**DISPLAY**: `HD1913_14_220617`  
**INCREMENTAL**: `2206171335`  
**SECURITY_PATCH**: `2022-06-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `OnePlus`  
**BRAND**: `OnePlus`  
**MODEL**: `HD1913`  
**PRODUCT**: `OnePlus7TPro_EEA`  
**BOARD**: `msmnile`  
**HARDWARE**: `qcom`  
**DEVICE**: `OnePlus7TPro`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by agnostic-apollo** [comment]
Well, not sure why this crash is happening. *Some say* its because resource ids are somehow invalid due to an update, or using vector icon instead of png like termux is for notification small icon. Reports exist on android issuetracker as well.

https://stackoverflow.com/a/26024747/14686958

Considering you are using F-Droid version instead of Github, not sure how to proceed since I can't send you a build to test. Maybe try going to Android Settings -> Apps -> See all apps -> Termux -> Notifications -> Disable `Termux App` notification. Maybe that will let you launch the app. If you don't have any important data, you can always try uninstalling the app and reinstalling.

**Comment by stalek71** [comment]
I think I found source of the problem. Something after termux/packages updates have broken the product.
In Logcat I found entries that led me to an installation of Termux:Styling package. When I installed it things started working already. Really strange as after the installation everything was ok.

**Comment by agnostic-apollo** [comment]
Was it installed before and did you uninstalled it?

**Comment by stalek71** [comment]
It has not been installed previously

czw., 24 lis 2022, 19:33 użytkownik agnostic-apollo <
***@***.***> napisał:

**Comment by peterpoko** [comment]
I uninstalled the old version and I'm unable to install the new version it keeps saying unknown error

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by stalek71** [comment]
Try installing Termux Styling or some other termux related packages first
