### ISSUE TITLE
[Bug]: its a wierd bug. Pasting an emoji with openboard crashes termux.

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-app#3242]
### Problem description

I use openboard https://github.com/openboard-team/openboard . with open board I can paste clipboard directly by long pressing the clipboard button of the keyboard. It also sends the enter key (i guess) bcs if I paste anything it also runs it as a command . 

I was pasting an emoji copied from browser and whenever I paste it using the clipboard button termux crashes. The hexadecimal value of it is `F09FA48C` and here is a link https://emojipedia.org/pinched-fingers/.

By default android doesn't support this emoji icon I guess bcs my device doesn't have it.

### Steps to reproduce the behavior.

Copy and paste the emoji with openboards clipboard button from this webpage https://emojipedia.org/pinched-fingers/ 

And/or 

```
echo f095a48c | xxd -r -p | termux-clipboard-set
```

And then paste it. Normal pasting doesn't crash Termux.

### What is the expected behavior?

Past the character to terminal from clipboard.

### System information

The app is from fdroid.

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-02-10 16:01:28.458 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-02-10 16:01:26.157 UTC`  

**Crash Message**:
```
Invalid code point: 56588
```

### Stacktrace

```
java.lang.IllegalArgumentException: Invalid code point: 56588
	at com.termux.terminal.TerminalSession.writeCodePoint(TerminalSession.java:185)
	at com.termux.view.TerminalView.inputCodePoint(TerminalView.java:832)
	at com.termux.view.TerminalView$2.sendTextToTerminal(TerminalView.java:383)
	at com.termux.view.TerminalView$2.commitText(TerminalView.java:315)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
##

### Software

**OS_VERSION**: `4.4.146`  
**SDK_INT**: `28`  
**RELEASE**: `9`  
**SECURITY_PATCH**: `2020-08-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**BOARD**: `MK008`  
**HARDWARE**: `mt6757`  

**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by Grimler91** [comment]
Thanks for the well written bug report! 

I believe this has been fixed on the master branch, the character at least shows up as a question mark when pasted on my device that has termux-app from master branch

**Comment by agnostic-apollo** [comment]
I can't reproduce it either on Android 7 and 11 and hexadecimal does not seem to be for the emoji. However, app will crash if an invalid code point is attempted to be  written, so I have fixed it locally, I don't know why it was thought of as a  good idea to crash the app for all the exceptions thrown for invalid input to terminal instead of just ignoring input.

Thanks for the report.

https://github.com/termux/termux-app/blob/2ac7fd1e565872d10b91157022485c13ab179524/terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java#L182-L187

https://emojipedia.org/emoji/%F0%9F%A4%8C/

**Comment by Anonymous2716** [comment]
Welcome and thanks. Then it will be fixed in the next version of termux I guess. And you can close this issue if fixed.

**Comment by twaik** [comment]
@agnostic-apollo 
I had simillar bug in termux-x11, it seems to be JNI related.
UTF-8 in JVM is pretty much special, you should get string content as 
```
"somestring".getBytes(java.nio.charset.StandardCharsets.UTF_8);
```
Converting string back from standard UTF-8 is also possible

```
byte[] b = {(byte) 99, (byte)97, (byte)116};
String s = new String(b, java.nio.charset.StandardCharsets.UTF_8);
```

**Comment by agnostic-apollo** [comment]
I am aware of modified utf8 requirements of JNI, but code point is calculated based on `Event.getUnicodeChar()` and not via strings.

https://github.com/termux/termux-app/blob/3b5018b4c79a2c2d218eb6fd570b2f2bebb8415a/terminal-view/src/main/java/com/termux/view/TerminalView.java#L778

**Comment by twaik** [comment]
Are you sure that is true unicode and not JVM related one? You can get the code with `String.from(unicode).getBytes(...)` and check if it is equal for needed keys. I think you can check it with physical keyboard with swiss-german layout, it had problematic symbols that crashed termux-x11.

**Comment by agnostic-apollo** [comment]
JNI would be involved, but crash doesn't happen there, `writeCodePoint()` does manual range check. We need to generate code point base on meta key states and kcm files, it's documented at https://github.com/termux/termux-app/blob/3b5018b4c79a2c2d218eb6fd570b2f2bebb8415a/terminal-view/src/main/java/com/termux/view/TerminalView.java#L633

**Comment by twaik** [comment]
I see you are converting multibyte characters manually. I think it will be much better to use `mbrtowc` in jni even in the case it does exactly the same thing. Combining it with `String.getBytes(charset)` trick will let OS (or at leas OS + libandroid_suport lib) do the trick right.

Also I want to ask: did you check `56588` codepoint?
