### ISSUE TITLE
[Bug]: Error while run script php

### ISSUE THREAD

**Issue by Nemeesis66** [termux/termux-app#3283]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-03-05 18:58:44.588 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-03-05 18:58:38.228 UTC`  

**Crash Message**:
```
Unable to start receiver com.termux.app.TermuxOpenReceiver: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://youtube.com/... flg=0x10000000 cmp=id.dana/.home.HomeTabActivity mCallingUid=10429 } from ProcessRecord{bed51fa 4021:com.termux/u0a429} (pid=4021, uid=10429) not exported from uid 10309
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start receiver com.termux.app.TermuxOpenReceiver: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://youtube.com/... flg=0x10000000 cmp=id.dana/.home.HomeTabActivity mCallingUid=10429 } from ProcessRecord{bed51fa 4021:com.termux/u0a429} (pid=4021, uid=10429) not exported from uid 10309
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4387)
	at android.app.ActivityThread.access$1800(ActivityThread.java:292)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://youtube.com/... flg=0x10000000 cmp=id.dana/.home.HomeTabActivity mCallingUid=10429 } from ProcessRecord{bed51fa 4021:com.termux/u0a429} (pid=4021, uid=10429) not exported from uid 10309
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2390)
	at android.os.Parcel.createException(Parcel.java:2374)
	at android.os.Parcel.readException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2299)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3717)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1055)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1013)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:413)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:413)
	at com.termux.app.TermuxOpenReceiver.onReceive(TermuxOpenReceiver.java:69)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4371)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1146)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1259)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:803)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1241)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1203)


```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0+b800f1c`  
**VERSION_CODE**: `118`  
**UID**: `10429`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c173,c257,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c173,c257,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_7`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.19.127+`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `RP1A.200720.011`  
**DISPLAY**: `RMX3201_11_C.16`  
**INCREMENTAL**: `1672253712794`  
**SECURITY_PATCH**: `2023-01-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `realme`  
**BRAND**: `realme`  
**MODEL**: `RMX3201`  
**PRODUCT**: `RMX3201T2`  
**BOARD**: `RM6765`  
**HARDWARE**: `mt6765`  
**DEVICE**: `RMX3201`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

php giffybot.php that's command while run on termux will error

### System information

* Termux application version: 0.118.0+b800f1c
* Android OS version: Android 11
* Device model: Realme C21

**Comment by agnostic-apollo** [comment]
Seems to be some ROM issue and not a termux issue specifically, other than the uncaught `SecurityException` (fixed locally). For some reason android is selecting your Dana Digital Wallet app activity to open the url even though it is not exported, i.e to be callable by other apps. Maybe in some previous app version it was exported, so try removing any urls set in `Open by default` in the app info for the app in android settings.

```xml
<activity android:name="id.dana.home.HomeTabActivity" android:exported="false" launchMode="singleTop" screenOrientation="portrait" windowSoftInputMode="adjustPan">
    <intent-filter>
        <action android:name="OPEN_NOTIFICATION_LAUNCHER"/>
        <category android:name="android.intent.category.DEFAULT"/>
    </intent-filter>
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:scheme="https"/>
    </intent-filter>
</activity>
```
