### ISSUE TITLE
[Bug]: Reboot after installing then crash

### ISSUE THREAD

**Issue by fumarate** [termux/termux-app#3284]
### Problem description

After installing, at the first time I launched it, the phone stopped working and reboot automatically. After rebooting, I relaunched it, it crashed with a report as follow.

### Steps to reproduce the behavior.

It is not pledged to always reproduce, it works well with my other phones.
1. Install the app and launch it
2. After rebooting, relaunch it

### What is the expected behavior?

Work well without rebooting or crashing.

### System information

Crash report is copied here.
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-02-19 03:02:50.167 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-02-19 03:01:42.273 UTC`  

**Crash Message**:
```
dlopen failed: "/data/app/~~ojbfGGr8mFVCNt8Ed2q4Ug==/com.termux-S22AbEdKAGbWlY--J1dQbg==/lib/arm64/libtermux.so" has bad ELF magic: 00000000
```

### Stacktrace

```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ojbfGGr8mFVCNt8Ed2q4Ug==/com.termux-S22AbEdKAGbWlY--J1dQbg==/lib/arm64/libtermux.so" has bad ELF magic: 00000000
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.termux.terminal.JNI.<clinit>(JNI.java:9)
	at com.termux.terminal.TerminalSession.initializeEmulator(TerminalSession.java:127)
	at com.termux.terminal.TerminalSession.updateSize(TerminalSession.java:105)
	at com.termux.view.TerminalView.updateSize(TerminalView.java:896)
	at com.termux.view.TerminalView.attachSession(TerminalView.java:250)
	at com.termux.app.terminal.TermuxTerminalSessionClient.setCurrentSession(TermuxTerminalSessionClient.java:277)
	at com.termux.app.terminal.TermuxTerminalSessionClient.addNewSession(TermuxTerminalSessionClient.java:355)
	at com.termux.app.TermuxActivity.lambda$onServiceConnected$1(TermuxActivity.java:370)
	at com.termux.app.TermuxActivity.lambda$onServiceConnected$1$TermuxActivity(Unknown Source:0)
	at com.termux.app.-$$Lambda$TermuxActivity$iAb3wbvCSw3C33cvEKUeEppeGmE.run(Unknown Source:2)
	at com.termux.app.TermuxInstaller.setupBootstrapIfNeeded(TermuxInstaller.java:102)
	at com.termux.app.TermuxActivity.onServiceConnected(TermuxActivity.java:362)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2188)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2221)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.9.337-perf-gb9a2ae16231b`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TQ1A.230205.002`  
**DISPLAY**: `TQ1A.230205.002`  
**INCREMENTAL**: `1676775680`  
**SECURITY_PATCH**: `2023-02-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `Xiaomi`  
**MODEL**: `MI 8 SE`  
**PRODUCT**: `sirius`  
**BOARD**: `sdm710`  
**HARDWARE**: `qcom`  
**DEVICE**: `sirius`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by agnostic-apollo** [comment]
Not an issue with termux app itself but likely a device specific issue. You can try to reinstall APK from F-Droid and see if that fixes the issue, assuming it always happens.
