### ISSUE TITLE
[Bug]: App Crash

### ISSUE THREAD

**Issue by A4-Tacks** [termux/termux-app#3315]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-03-23 17:59:34.672 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-03-23 17:59:33.484 UTC`  

**Crash Message**:
```
Failed to allocate a 2147483664 byte allocation with 10294821 free bytes and 374MB until OOM, target footprint 20589645, growth limit 402653184
```

### Stacktrace

```
java.lang.OutOfMemoryError: Failed to allocate a 2147483664 byte allocation with 10294821 free bytes and 374MB until OOM, target footprint 20589645, growth limit 402653184
	at com.termux.terminal.TerminalEmulator.resize(TerminalEmulator.java:383)
	at com.termux.terminal.TerminalSession.updateSize(TerminalSession.java:108)
	at com.termux.view.TerminalView.updateSize(TerminalView.java:896)
	at com.termux.view.TerminalView.setTextSize(TerminalView.java:450)
	at com.termux.app.terminal.TermuxTerminalViewClient.changeFontSize(TermuxTerminalViewClient.java:490)
	at com.termux.app.terminal.TermuxTerminalViewClient.onScale(TermuxTerminalViewClient.java:167)
	at com.termux.view.TerminalView$1.onScale(TerminalView.java:144)
	at com.termux.view.GestureAndScaleRecognizer$3.onScale(GestureAndScaleRecognizer.java:85)
	at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:374)
	at com.termux.view.GestureAndScaleRecognizer.onTouchEvent(GestureAndScaleRecognizer.java:93)
	at com.termux.view.TerminalView.onTouchEvent(TerminalView.java:572)
	at android.view.View.dispatchTouchEvent(View.java:13699)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:741)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:2013)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4180)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:687)
	at android.view.View.dispatchPointerEvent(View.java:13962)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6420)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6215)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5623)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5781)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5631)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5838)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5631)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8701)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8621)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8574)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8959)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:239)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:222)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8862)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9033)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:904)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.14.116`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `HUAWEIBAH3-W09`  
**DISPLAY**: `BAH3-W09 2.0.0.230(C00E165R1P165)`  
**INCREMENTAL**: `102.0.0.230C00`  
**SECURITY_PATCH**: `2020-11-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HUAWEI`  
**MODEL**: `BAH3-W09`  
**PRODUCT**: `BAH3-W09`  
**BOARD**: `BAH3-W09`  
**HARDWARE**: `kirin810`  
**DEVICE**: `HWBAH3`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

I am currently printing continuously, with screen zooming, keyboard retraction, and keyboard expansion. At a certain moment, the extended keyboard prompt text disappears, and the entire text turns black. The software crashes when you operate again

### What is the expected behavior?

no crash

### System information

* Termux application version: 0.118.0
* Android OS version: HarmonyOS 2.0.0
* Device model:

**Comment by agnostic-apollo** [comment]
Reduce what you printing on terminal, especially if you have increased number of terminal rows or are opening too many terminals.
