### ISSUE TITLE
Several Permission Issue when using python virtualenv and npm

### ISSUE THREAD

**Issue by whao** [termux/termux-app#351]
For npm issue, please see here https://github.com/npm/npm/issues/17568.

**Virtualenv**

First, I `mkdir` a `Developer` directory under `/storage/emulated/0`, and then `link -s` it to termux home `~/storage/developer`. Then I tried to set up a virtualenv directory by using `virtualenv foo` but I got these permission errors:
```
Using base prefix '/data/data/com.termux/files/usr'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/virtualenv.py", line 351, in copyfile
    os.symlink(srcpath, dest)
PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/usr/lib/python3.6/lib-dynload' -> '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/virtualenv.py", line 1130, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/virtualenv.py", line 354, in copyfile
    copyfileordir(src, dest, symlink)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/virtualenv.py", line 329, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/data/data/com.termux/files/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_heapq.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_heapq.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_opcode.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_opcode.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/audioop.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/audioop.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/parser.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/parser.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/xxlimited.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/xxlimited.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_codecs_iso2022.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_codecs_iso2022.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_crypt.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_crypt.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/binascii.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/binascii.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_multiprocessing.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_multiprocessing.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_asyncio.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_asyncio.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_sha256.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_sha256.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/mmap.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/mmap.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_curses.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_curses.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_testbuffer.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_testbuffer.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/array.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/array.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/resource.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/resource.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_ctypes_test.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_ctypes_test.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/syslog.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/syslog.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_elementtree.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_elementtree.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_sha1.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_sha1.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/grp.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/grp.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_sha3.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_sha3.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/select.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/select.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_md5.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_md5.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_bz2.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_bz2.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_json.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_json.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_codecs_cn.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_codecs_cn.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_testimportmultiple.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_testimportmultiple.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/unicodedata.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/unicodedata.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/termios.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/termios.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_struct.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_struct.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_ssl.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_gdbm.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_gdbm.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/readline.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/readline.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_ctypes.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_testmultiphase.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_testmultiphase.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_curses_panel.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_curses_panel.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_sha512.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_sha512.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_random.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_random.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_lsprof.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_lsprof.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_codecs_jp.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_codecs_jp.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_lzma.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_lzma.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_multibytecodec.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_multibytecodec.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_testcapi.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_testcapi.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/ossaudiodev.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/ossaudiodev.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_hashlib.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_hashlib.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_sqlite3.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_sqlite3.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_socket.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_socket.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/zlib.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/zlib.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_decimal.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_decimal.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_datetime.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_datetime.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_blake2.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_blake2.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_codecs_tw.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_codecs_tw.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_codecs_hk.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_codecs_hk.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_csv.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_csv.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_codecs_kr.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_codecs_kr.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/fcntl.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/fcntl.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/cmath.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/cmath.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/pyexpat.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/pyexpat.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_bisect.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_bisect.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/math.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/math.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload/_pickle.cpython-36m.so', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload/_pickle.cpython-36m.so', '[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/lib-dynload', '/storage/emulated/0/Developers/foo/lib/python3.6/lib-dynload', '[Errno 1] Operation not permitted')]
```
But everything goes find when using in termux home directory. It is like it cannot be executed in `/storage/emulated/0` or outside environment but termux has already granted the storage permission.

Anyone has the same issues?

**Comment by wardrich** [comment]
I'm running into the same issue.  I can't `cat` the files or anything. I even tried to `chmod 777` the file via an external file browser just to see if I could get it to budge at all, and still got permission errors even just trying to use `cat`.

**Comment by Zebz13** [comment]
I had the same issue. But now I can access the .py files in  the /data/data/com.termux/  folder.

To fix the issue regarding errno13 when opening files inside the home folder just run restorecon

su
restorecon -v filename

Found the solution here : https://wiki.termux.com/wiki/FAQ
