### ISSUE TITLE
Report Text

### ISSUE THREAD

**Issue by saros6971** [termux/termux-app#3513]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-07-19 07:00:07.322 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-07-18 07:00:10.466 UTC`  

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{73a9ba6 u0a248 LAST idle change:procstateprocadj procs:0 seq(13310722,13306426)}
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{73a9ba6 u0a248 LAST idle change:procstateprocadj procs:0 seq(13310722,13306426)}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{73a9ba6 u0a248 LAST idle change:procstateprocadj procs:0 seq(13310722,13306426)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1981)
	at android.app.ContextImpl.startService(ContextImpl.java:1927)
	at android.content.ContextWrapper.startService(ContextWrapper.java:834)
	at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:242)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.14.113-25950142`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: *************  
**DISPLAY**: ****************`  
**INCREMENTAL**: **********  
**SECURITY_PATCH**: `2023-06-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-M21**  
**PRODUCT**: `m21ins`  
**BOARD**: `exynos9611`  
**HARDWARE**: `exynos9611`  
**DEVICE**: `m21`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by shanu-user** [comment]
Hello saros6971, I am new to open source. Let me give it a try. Please assign me this issue.

**Comment by agnostic-apollo** [comment]
This was partially already fixed in master branch and real fix will be pushed later from my local changes.
