### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-app#3583]
### Feature description

Allow permission to accessabity for the Android app

### Additional information

Allow app to set accessibility feature or give me an alternative.

**Comment by twaik** [comment]
What for?

**Comment by FalconSN** [comment]
`input` in `/system/bin` can be used as user, but requires `INJECT_EVENT` permission:
```
~ $ input tap 500 500

Exception occurred while executing 'tap':
java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:900)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1163)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1192)
        at com.android.server.input.InputShellCommand.injectMotionEvent(InputShellCommand.java:181)
        at com.android.server.input.InputShellCommand.sendTap(InputShellCommand.java:382)
        at com.android.server.input.InputShellCommand.runTap(InputShellCommand.java:376)
        at com.android.server.input.InputShellCommand.onCommand(InputShellCommand.java:235)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.input.InputManagerService.onShellCommand(InputManagerService.java:3889)
        at android.os.Binder.shellCommand(Binder.java:1049)
        at android.os.Binder.onTransact(Binder.java:877)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:1144)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1244)
```
This limits the usage of Termux for non-rooted users. Maybe it can be implemented via Acessibility?

**Comment by twaik** [comment]
`android.permission.INJECT_EVENTS` is a system rermission. And can be granted only to system apps, signed with a system certificate. 

Generating input events can be implemented with reguilar Android application, but not an application that can be started with termux command line.

**Comment by FalconSN** [comment]
Then I'm out of ideas to support this request. Thank you for the info.

**Comment by agnostic-apollo** [comment]
Use `adb` to run `input` command.

https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/
