### ISSUE TITLE
[Bug]: Missing android.permission.INTERACT_ACROSS_USERS permission

### ISSUE THREAD

**Issue by errr-maxx** [termux/termux-app#3718]
### Problem description

Executing `echo "$(settings put system a 0 </dev/null 2>&1)"` result in error:
```Exception occurred while executing 'put':
java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=12215, uid=10324 requires android.permission.INTERACT_ACROSS_USERS
        at com.android.server.am.UserController.checkGetCurrentUserPermissions(UserController.java:2613)
        at com.android.server.am.UserController.getCurrentUser(UserController.java:2618)
        at com.android.server.am.ActivityManagerService.getCurrentUser(ActivityManagerService.java:17495)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:260)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1050)
        at android.os.Binder.onTransact(Binder.java:877)
        at android.os.Binder.execTransactInternal(Binder.java:1286)
        at android.os.Binder.execTransact(Binder.java:1245)
```
because Termux does not request `android.permission.INTERACT_ACROSS_USERS` "development" permission

### Steps to reproduce the behavior.

Run `echo "$(settings put system a 0 </dev/null 2>&1)"`

### What is the expected behavior?

`settings put` works

### System information

* Termux application version: 0.118.0+3b5018b
* Android OS version: 13
* Device model: Tecno Camon 20 Pro 5G (CK8n)

**Comment by twaik** [comment]
No need to bump topic. It will not help solving the issue.

**Comment by agnostic-apollo** [comment]
You can bypass that error by running `system put --user 0`, but that will fail as well with the `java.lang.SecurityException: You either need MANAGE_USERS, CREATE_USERS or QUERY_USERS permission to: query user` error, which are all `signature`/`privileged` permissions. Even defining `INTERACT_ACROSS_USERS` and granting it and `WRITE_SECURE_SETTINGS` will result in same error. Settings `global`, `secure` and `system` settings with `settings` command all fail with same error on Android `11` and `14`. Use `adb` provided by `android-tools` package or use root instead.

https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/core/res/AndroidManifest.xml;l=3098-3151

https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/packages/SettingsProvider/src/com/android/providers/settings/SettingsService.java;l=266;bpv=0

https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/pm/UserManagerService.java;l=3350
