### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by BarryLhm** [termux/termux-app#3765]
### Problem description

Termux immediately crashes after launch because "android.premission.FOREGROUND_SERVICE" problem

Bug report below:

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-12-30 02:30:54.859 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-12-30 02:30:54.104 UTC`  

**Crash Message**:
```
Unable to create service com.termux.app.TermuxService: java.lang.SecurityException: Permission Denial: startForeground from pid=14666, uid=10221 requires android.permission.FOREGROUND_SERVICE
```

### Stacktrace

```
java.lang.RuntimeException: Unable to create service com.termux.app.TermuxService: java.lang.SecurityException: Permission Denial: startForeground from pid=14666, uid=10221 requires android.permission.FOREGROUND_SERVICE
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3611)
	at android.app.ActivityThread.access$1500(ActivityThread.java:207)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1717)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6831)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=14666, uid=10221 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5084)
	at android.app.Service.startForeground(Service.java:695)
	at com.termux.app.TermuxService.runStartForeground(TermuxService.java:196)
	at com.termux.app.TermuxService.onCreate(TermuxService.java:121)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3599)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9627)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1229)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:904)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:21200)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:10627)


```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.14.94+`  
**SDK_INT**: `28`  
**RELEASE**: `9`  
**ID**: `PPR1.180610.011`  
**DISPLAY**: `PPR1.180610.011`  
**INCREMENTAL**: `V99.0.3.0.PGGCNXM`  
**SECURITY_PATCH**: `2019-12-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `Redmi`  
**MODEL**: `Redmi Note 8 Pro`  
**PRODUCT**: `begonia`  
**BOARD**: `begonia`  
**HARDWARE**: `mt6785`  
**DEVICE**: `begonia`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

Launch Termux

### What is the expected behavior?

Termux starts correctly

### System information

* Termux application version:0.118
* Android OS version:9
* Device model:begonia

**Comment by BarryLhm** [comment]
PS:
Please see system version 99.0.3 as 11.0.3 because it's fake for ban miui updates
PPS:
 I couldn't find any permission switch in settings and this maybe a system problem

**Comment by agnostic-apollo** [comment]
This will be fixed in next version, partial is available in github action builds and fully hasn't been pushed.
