### ISSUE TITLE
[Bug]: termux crash

### ISSUE THREAD

**Issue by cidz-lab** [termux/termux-app#3786]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2024-01-13 11:39:31.646 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2024-01-13 09:59:58.739 UTC`  

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{415c85e u0a545 TPSL idle procs:1 seq(0,0,0)}
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{415c85e u0a545 TPSL idle procs:1 seq(0,0,0)}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{415c85e u0a545 TPSL idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1687)
	at android.app.ContextImpl.startService(ContextImpl.java:1632)
	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
	at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:242)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
	... 11 more

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.4.177-22392479`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `QP1A.190711.020`  
**DISPLAY**: `QP1A.190711.020.M205GDXU7CVG2`  
**INCREMENTAL**: `M205GDXU7CVG2`  
**SECURITY_PATCH**: `2022-08-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-M205G`  
**PRODUCT**: `m20ltedx`  
**BOARD**: `exynos7904`  
**HARDWARE**: `exynos7904`  
**DEVICE**: `m20lte`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

I dont understad

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Stan-Di** [comment]
I have a similar problem on an H618 processor:

`## Crash Details

**Crash Thread**: `Thread[main,5,main]`
**Crash Timestamp**: `2024-03-17 13:57:58.905 UTC`

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux
.app.TermuxActivity}: java.lang.RuntimeException: bindServic
e() failed
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start activity Compone
ntInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.
RuntimeException: bindService() failed
        at android.app.ActivityThread.performLaunchActivity(
ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(A
ctivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.
execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor
.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor
.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(Activi
tyThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:1
06)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.ja
va:7854)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgs
Caller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteIni
t.java:1182)
Caused by: java.lang.RuntimeException: bindService() failed
        at com.termux.app.TermuxActivity.onCreate(TermuxActi
vity.java:247)
        at android.app.Activity.performCreate(Activity.java:
8050)

     at android.app.Activity.performCreate(Activity.java:
8030)
        at android.app.Instrumentation.callActivityOnCreate(
Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(
ActivityThread.java:3608)
        ... 12 more

```
##

## Termux App Info

**APP_NAME**: `Termux`
**PACKAGE_NAME**: `com.termux`
**VERSION_NAME**: `0.118.0`
**VERSION_CODE**: `118`
**TARGET_SDK**: `28`
**IS_DEBUGGABLE_BUILD**: `false`
**APK_RELEASE**: `F-Droid`
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499E
C3CCAF61E96E8E1CE70766B9474672CE427334D41C42`
##

## Device Info

### Software

**OS_VERSION**: `5.4.125+`
**SDK_INT**: `31`
**RELEASE**: `12`
**ID**: `SP1A.211105.004`
**DISPLAY**: `apollo_p1-userdebug 12 SP1A.211105.004 2023080
2.104736`
**INCREMENTAL**: `20230802.104736`
**SECURITY_PATCH**: `2022-02-05`
**IS_DEBUGGABLE**: `1`
**IS_TREBLE_ENABLED**: `true`
**TYPE**: `userdebug`
**TAGS**: `release-keys`

### Hardware

**MANUFACTURER**: `Oranth`
**BRAND**: `google`
**MODEL**: `TX68`
**PRODUCT**: `raven`
**BOARD**: `exdroid`
**HARDWARE**: `sun50iw9p1`
**DEVICE**: `raven`
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`
##`

Can someone help solve this bug? My Termux starts 3 times and works fine after that, but because of the first crashes Termux:Boot does not work.

**Comment by Cigydd** [comment]
Having a similar issue. Just activated my phone's screen, activated a running Termux terminal session, and got this crash report.

## Report Info


**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2024-10-31 04:35:36.839 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2024-10-31 03:57:34.379 UTC`  

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{ff5aad7 u0a563 TPSL idle change:procadj procs:0 seq(1970864,1970862)} caps=------
```


### Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{ff5aad7 u0a563 TPSL idle change:procadj procs:0 seq(1970864,1970862)} caps=------
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{ff5aad7 u0a563 TPSL idle change:procadj procs:0 seq(1970864,1970862)} caps=------
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2016)
	at android.app.ContextImpl.startService(ContextImpl.java:1961)
	at android.content.ContextWrapper.startService(ContextWrapper.java:842)
	at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:242)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	... 12 more

```
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##


## Device Info

### Software

**OS_VERSION**: `4.14.190-perf-28693687-abA525FXXU8FXH1`  
**SDK_INT**: `34`  
**RELEASE**: `14`  
**ID**: `UP1A.231005.007`  
**DISPLAY**: `UP1A.231005.007.A525FXXU8FXH1`  
**INCREMENTAL**: `A525FXXU8FXH1`  
**SECURITY_PATCH**: `2024-08-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-A525F`  
**PRODUCT**: `a52qnseea`  
**BOARD**: `atoll`  
**HARDWARE**: `qcom`  
**DEVICE**: `a52q`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##
