### ISSUE TITLE
Starting am from termux

### ISSUE THREAD

**Issue by ATumbler** [termux/termux-app#380]
I wrote an API for my own contacts and put the interface on the terminal. As a language for processing decided to choose a python. There is no python3 in the root directory. In the directory termux there is no access to root. 
when I write:

    am start -a android.intent.action.CALL -d tel:10287281

termux say

    Starting: Intent { act=android.intent.action.CALL dat=tel:x }
java.lang.SecurityException: Permission Denial: startActivity asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
        at android.os.Parcel.readException(Parcel.java:1620)
        at android.os.Parcel.readException(Parcel.java:1573)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2713)
        at com.android.commands.am.Am.runStart(Am.java:875)
        at com.android.commands.am.Am.onRun(Am.java:359)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:100)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:256)

I know this works in system / bin. But there is no python3 that I need. Shell> python3> shell (call).

**Comment by Neo-Oli** [comment]
What you want to do you can do with the [Termux Api](https://termux.com/add-on-api.html). 
`termux-telephony-call 0123456789`

**Comment by fornwall** [comment]
In general you need to specify `--user 0` when calling `am` under Termux.
