### ISSUE TITLE
Crash using ARC on Asus C300 Chromebook

### ISSUE THREAD

**Issue by pepijndevos** [termux/termux-app#390]
After reading https://blog.lessonslearned.org/building-a-more-secure-development-chromebook/ I decided to try this on my Chromebook. As this laptop does not yet officially support Google Play, but does support the ARC welder app, I attempted to use that.

After importing the APK (version 53 from F-droid), it displays the following error message:

> Unfortunately Termux has stopped

I inspected the app and the console prints the following stacktrace:

```
stack_trace: java.lang.RuntimeException
	at android.os.Process$1.run(Process.java:536)
Caused by java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at android.os.Process$1.run(Process.java:529)
Caused by java.lang.RuntimeException
	at com.termux.terminal.JNI.createSubprocess(Native Method)
	at com.termux.terminal.i.b(Unknown Source)
	at com.termux.terminal.i.a(Unknown Source)
	at com.termux.view.TerminalView.b(Unknown Source)
	at com.termux.view.TerminalView.a(Unknown Source)
	at com.termux.app.TermuxActivity.b(Unknown Source)
	at com.termux.app.TermuxActivity.a(Unknown Source)
	at com.termux.app.TermuxActivity$4.run(Unknown Source)
	at com.termux.app.d.a(Unknown Source)
	at com.termux.app.TermuxActivity.onServiceConnected(Unknown Source)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1203)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1220)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5522)
	...3 more
```

This may be related to #49, but the error message is different and looking at other issues and the linked blog post, it definitely works on Chrome these days.

**Comment by fornwall** [comment]
Unfortunately AFAIK the ARC welder app is too limited to run Termux on, and you would need to await official Google Play on the device!
