### ISSUE TITLE
[Bug]: poco x3 pro (no root) package installer fails (log file) 

### ISSUE THREAD

**Issue by Fohsap** [termux/termux-app#3943]
### Problem description

java.lang.SecurityException: Can't install packages while in secure FRP
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.commit(IPackageInstallerSession.java:794)
	at android.content.pm.PackageInstaller$Session.commit(PackageInstaller.java:1550)
	at com.android.packageinstaller.InstallInstalling$InstallingAsyncTask.onPostExecute(InstallInstalling.java:371)
	at com.android.packageinstaller.InstallInstalling$InstallingAsyncTask.onPostExecute(InstallInstalling.java:293)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerSession.markAsSealed(PackageInstallerSession.java:2106)
	at com.android.server.pm.PackageInstallerSession.commit(PackageInstallerSession.java:1848)
	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:385)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)

### Steps to reproduce the behavior.

Running compatible installers with the default package installer on a clean phone returns this error similar error occurs installing f-droid. 

### What is the expected behavior?

Install normally. Playstore version works to install so I'm not sure why this doesn't. 

### System information

* Termux application version: latest, 0.118. 0 
* Android OS version: Miui 13. 0.5 global stable, android 12 skq 1. 211006.01
* Device model: poco x3 pro.

**Comment by twaik** [comment]
Seems like it is issue of your firmware and not related to termux.

**Comment by a52294602-ship-it** [comment]
![Image](https://github.com/user-attachments/assets/ed03b941-186d-4015-a964-c05b816882c7)
