### ISSUE TITLE
[Bug]: 3rd party app open in termux broken in latest version

### ISSUE THREAD

**Issue by Doc-4** [termux/termux-app#4024]
### Problem description

Attempting to use a third-party app to open Termux fails. Allow external apps is enabled in Termux properties, and appropriate permissions have been granted where relevant.

### Steps to reproduce the behavior.

Enable external apps, open a compatible file manager and attempt to open working directory using Termux, video provided 

https://github.com/termux/termux-app/assets/60247583/5b59f583-84bc-4721-b676-da6762e6993b

### What is the expected behavior?

The two file managers tested are able to open Termux in the working directory.

### System information

* Termux application version: v0.119.0-beta.1
* Android OS version: GrapheneOS Android 14
* Device model: Pixel 8 Pro

**Comment by agnostic-apollo** [comment]
Did you restart app or run `termux-reload-settings`? Do those apps even have RUN_COMMAND permission granted to them?

`0.118.1` requires that app is restarted after installation, otherwise default `termux.properties` added by login shell doesn't get picked up, but that doesn't apply to you.

**Comment by Doc-4** [comment]
The app has been restarted and settings reloaded numerous times since then, the appropriate permissions have been granted:
![Screenshot_20240620-092357](https://github.com/termux/termux-app/assets/60247583/8f237049-14d4-4981-8827-d2edc703a801)

**Comment by agnostic-apollo** [comment]
mixplorer version?

**Comment by Doc-4** [comment]
No, Termux version. Didn't work with material files either.

**Comment by agnostic-apollo** [comment]
As always, MiXplorer is broken, both latest stable and beta, older versions have improper usage of RUN_COMMAND intent (search in other issues/discussions).

It is stuck in an infinite loop for permission check, until app crashes.

```
com.mixplorer.beta E at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
	at com.mixplorer.activities.a.onRequestPermissionsResult(SourceFile:20)
	at android.app.Activity.onRequestPermissionsResult(Activity.java:5768)
	at android.app.Activity.requestPermissions(Activity.java:5702)
	at android.app.Activity.requestPermissions(Activity.java:5624)
om.mixplorer.beta E java.lang.StackOverflowError: stack size 8188KB
```

MaterialFiles does not support Termux and only jackpal terminal.

- https://github.com/zhanghai/MaterialFiles/blob/a4a524041119e303cdec125924bce617641c604e/app/src/main/java/me/zhanghai/android/files/terminal/Terminal.kt
- https://github.com/zhanghai/MaterialFiles/blob/a4a524041119e303cdec125924bce617641c604e/app/src/main/java/me/zhanghai/android/files/filelist/FileListFragment.kt#L758
- https://github.com/termux/termux-app/issues/1070

RUN_COMMAND intent works fine for latest beta and there is not issue with Termux, report issues to respective devs of other apps.

**Comment by Doc-4** [comment]
I see, the regression was mixplorer or it was a happily accident it worked before at all. I'll go report it there, sorry for the erroneous report.
