### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'prompt_toolkit'

### ISSUE THREAD

**Issue by gitra123** [termux/termux-app#4076]
### Problem description

I tried installing "selectmenu", then it gives an error (is prompt_toolkit installed):
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1                                                                                                        ╰─> [24 lines of output]
      Traceback (most recent call last):                                                                                      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()                                                                                                              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main                                                                                                 json_out['return_val'] = hook(**hook_input['kwargs'])                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel                                                                         return hook(config_settings)                                                                                                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-kpa76ljr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel                                                                    return self._get_build_requires(config_settings, requirements=[])                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-kpa76ljr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()                                                                                                    File "/data/data/com.termux/files/usr/tmp/pip-build-env-kpa76ljr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-kpa76ljr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup                                                                                       exec(code, locals())
        File "<string>", line 5, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-d7bhk8o1/selectmenu_a25aa5c540e4465b80b4421d6cc8a3a2/selectmenu/__init__.py", line 4, in <module>                                                                                       from selectmenu.core import SelectMenu                                                                              File "/data/data/com.termux/files/usr/tmp/pip-install-d7bhk8o1/selectmenu_a25aa5c540e4465b80b4421d6cc8a3a2/selectmenu/core.py", line 6, in <module>                                                                                           from prompt_toolkit.token import Token                                                                            **ModuleNotFoundError: No module named 'prompt_toolkit'**                                              [end of output]

### Steps to reproduce the behavior.

`pip install selectmenu`

### What is the expected behavior?

Install selectmenu

### System information

* Termux application version: 0.119.1
* Android OS version: Android 11 Red velvet
* Device model: brazilian model>BLU b6

**Comment by Biswa96** [comment]
The error is not related to termux. I would suggest to learn Python language first before jumping in advanced use cases.

**Comment by gitra123** [comment]
> The error is not related to termux. I would suggest to learn Python language first before jumping in advanced use cases.

fr, this was a project error
