### ISSUE TITLE
I can't run the script(

### ISSUE THREAD

**Issue by sxgphIre** [termux/termux-app#4090]
### Problem description

All requirements from requirements.txt were met, but the error could not be avoided(

### Steps to reproduce the behavior.

I suffered for 3 hours, but nothing helped. And there was nothing useful for me on the Internet.

### What is the expected behavior?

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/data/data/com.termux/files/usr/bin/python"
  * The NumPy version is: "2.0.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sdcard/Download/AyuGram/Valkyrie/valkyrie.py", line 24, in <module>
    import pytesseract
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pytesseract/pytesseract.py", line 34, in <module>
    from numpy import ndarray
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

### System information

* Termux application version:?
* Android OS version:14
* Device model:redmi note 13

**Comment by TomJo2000** [comment]
You seem to be attempting to build `numpy`.
Please be aware we have a `python-numpy` package available in the repositories,
which should most likely work for your needs.

If you still need to compile it from source please see:
- termux/termux-packages#19126

**Comment by sxgphIre** [comment]
Thank you,It helped a lot, but now there is another error (. if you know how to solve it please help?

**Comment by sxgphIre** [comment]
I'm sorry, I've already decided)
