### ISSUE TITLE
[Bug]: expand notification-bar using `cmd` failed 

### ISSUE THREAD

**Issue by HusniMuhammad** [termux/termux-app#4248]
### Problem description

Possible Due to this missing permission 

```
Exception occurred while executing 'expand-notifications':
java.lang.SecurityException: StatusBarManagerService: Neither user 10472 nor current process has android.permission.EXPAND_STATUS_BAR.
        at android.app.ContextImpl.enforce(ContextImpl.java:2018)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2046)
        at com.android.server.statusbar.StatusBarManagerService.enforceExpandStatusBar(StatusBarManagerService.java:1076)
        at com.android.server.statusbar.StatusBarManagerService.expandNotificationsPanel(StatusBarManagerService.java:556)
        at com.android.server.statusbar.StatusBarShellCommand.runExpandNotifications(StatusBarShellCommand.java:113)
        at com.android.server.statusbar.StatusBarShellCommand.onCommand(StatusBarShellCommand.java:54)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.statusbar.StatusBarManagerService.onShellCommand(StatusBarManagerService.java:1446)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at com.android.internal.statusbar.IStatusBarService$Stub.onTransact(IStatusBarService.java:1145)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
```

### Steps to reproduce the behavior.

```
cmd statusbar expand-notifications
```

### What is the expected behavior?

Expansion of notification-bar

### System information
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~LkYORvIv7C6UCW4kjISZRQ==/com.termux-9Wz4ANftMUKJoKDOTRGxCA==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=29502
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c216,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c216,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10472
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+062c977
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+062c977
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
curl/stable 8.11.0 arm [upgradable from: 8.10.1-2]
gpgme/stable 1.24.0 arm [upgradable from: 1.23.2-3]
gpgmepp/stable 1.24.0 arm [upgradable from: 1.23.2-3]
inetutils/stable 2.5 arm [upgradable from: 2.4-2]
libc++/stable 27c arm [upgradable from: 27b]
libcurl/stable 8.11.0 arm [upgradable from: 8.10.1-2]
libexpat/stable 2.6.4 arm [upgradable from: 2.6.3]
libheif/stable 1.19.2 arm [upgradable from: 1.19.1]
libmediainfo/stable 24.11 arm [upgradable from: 24.06-1]
mediainfo/stable 24.11 arm [upgradable from: 24.06-1]
termux-tools version:
1.44.3
Android version:
11
Kernel build information:
Linux localhost 4.14.193+-ab478 #1 SMP PREEMPT Thu May 9 16:42:40 CST 2024 armv8l Android
Device manufacturer:
realme
Device model:
RMX3231
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.widget versionCode:13

**Comment by HusniMuhammad** [comment]
@Balles9 what is this?

**Comment by N9097** [comment]
كيف تخترق حساب الفيسبوك

**Comment by HusniMuhammad** [comment]
System level app permission needed for this to continue, so device need to  be rooted
