### ISSUE TITLE
[Bug]: app crashed after being launched

### ISSUE THREAD

**Issue by twaik** [termux/termux-app#4279]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2024-11-27 11:46:47.428 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2024-11-27 11:46:45.934 UTC`  

**Crash Message**:
```
Attempt to invoke virtual method 'void android.widget.SeekBar.setThumbTintList(android.content.res.ColorStateList)' on a null object reference
```

### Stacktrace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.SeekBar.setThumbTintList(android.content.res.ColorStateList)' on a null object reference
 at com.android.internal.widget.DecorCaptionView.setDecorCaptionShade(DecorCaptionView.java:2128)
 at com.android.internal.widget.DecorCaptionView.onConfigurationChanged(DecorCaptionView.java:1056)
 at com.android.internal.policy.DecorView.onWindowingModeChanged(DecorView.java:4479)
 at com.android.internal.policy.PhoneWindow.setActivityCurrentConfig(PhoneWindow.java:4385)
 at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6653)
 at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6562)
 at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6927)
 at android.app.servertransaction.MoveToDisplayItem.execute(MoveToDisplayItem.java:52)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8762)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.1`  
**VERSION_CODE**: `1000`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.19.87-27231340`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TP1A.220624.014`  
**DISPLAY**: `TP1A.220624.014.G780FXXSKFXJ4`  
**INCREMENTAL**: `G780FXXSKFXJ4`  
**SECURITY_PATCH**: `2024-10-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-G780F`  
**PRODUCT**: `r8sxx`  
**BOARD**: `exynos990`  
**HARDWARE**: `exynos990`  
**DEVICE**: `r8s`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by twaik** [comment]
There are no app-related functions in the stacktrace, probably a firmware bug.

**Comment by twaik** [comment]
@agnostic-apollo should we keep it or close it?

**Comment by agnostic-apollo** [comment]
No, seems like a system bug. If it is reproducible, then let us know, but seems to be occurring before Termux app is handled control.
