### ISSUE TITLE
[Bug]: Random crash

### ISSUE THREAD

**Issue by Rufim** [termux/termux-app#4294]
### Problem description

. 

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2024-12-09 12:27:05.131 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2024-12-09 12:27:00.010 UTC`  

**Crash Message**:
```
Attempt to read from field 'int com.android.server.inputmethod.InputMethodManagerService$ClientState.mUid' on a null object reference in method 'boolean com.android.server.inputmethod.InputMethodManagerService.isImeClientFocused(android.os.IBinder, com.android.server.inputmethod.InputMethodManagerService$ClientState)'
```

### Stacktrace

```
java.lang.NullPointerException: Attempt to read from field 'int com.android.server.inputmethod.InputMethodManagerService$ClientState.mUid' on a null object reference in method 'boolean com.android.server.inputmethod.InputMethodManagerService.isImeClientFocused(android.os.IBinder, com.android.server.inputmethod.InputMethodManagerService$ClientState)'
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.showSoftInput(IInputMethodManager.java:855)
	at android.view.inputmethod.IInputMethodManagerGlobalInvoker.showSoftInput(IInputMethodManagerGlobalInvoker.java:306)
	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:2194)
	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:2156)
	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:2091)
	at com.termux.shared.view.KeyboardUtils.showSoftKeyboard(KeyboardUtils.java:71)
	at com.termux.app.terminal.TermuxTerminalViewClient.lambda$getShowSoftKeyboardRunnable$0$TermuxTerminalViewClient(TermuxTerminalViewClient.java:651)
	at com.termux.app.terminal.-$$Lambda$TermuxTerminalViewClient$BE9D5qAMZz5Fz7pW2tSQZk2KB5w.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:295)
	at android.app.ActivityThread.main(ActivityThread.java:8702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.119.0-beta.1`  
**VERSION_CODE**: `1020`  
**UID**: `10267`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c11,c257,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c11,c257,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_7`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `5.10.168-android12-9-g7395a3866bb1`  
**SDK_INT**: `34`  
**RELEASE**: `14`  
**ID**: `UKQ1.231025.001`  
**DISPLAY**: `TB320FC_CN_OPEN_USER_Q00031.0_U_ZUI_16.0.336_ST_240626`  
**INCREMENTAL**: `TB320FC_CN_OPEN_USER_Q00031.0_U_ZUI_16.0.336_ST_240626`  
**SECURITY_PATCH**: `2024-05-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  
**MAX_PHANTOM_PROCESSES**: - (*Requires `DUMP` and `PACKAGE_USAGE_STATS` permission*)  
**MONITOR_PHANTOM_PROCS**: `true`  
**DEVICE_CONFIG_SYNC_DISABLED**: -  

### Hardware

**MANUFACTURER**: `LENOVO`  
**BRAND**: `Lenovo`  
**MODEL**: `TB320FC`  
**PRODUCT**: `TB320FC_PRC`  
**BOARD**: `taro`  
**HARDWARE**: `qcom`  
**DEVICE**: `TB320FC`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

## Report Info
I not 100% sure when it happened. Seems that when I return focus go desktop X11 from other screen

### What is the expected behavior?

Not crash

### System information

* Termux application version: 0.119.0-beta.1
* Android OS version: 14
* Device model: TB320FC

**Comment by twaik** [comment]
Probably the code in `com.termux.shared.view.KeyboardUtils.showSoftKeyboard` should be wrapped to try-catch block to avoid crashing.
