### ISSUE TITLE
[Bug]: Unable to install bootstrap

### ISSUE THREAD

**Issue by rsedlac** [termux/termux-app#4328]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2024-12-29 16:41:21.723 UTC`  
##

## Termux Bootstrap Error

``````
(-1) Termux Bootstrap Second Stage Command:
Previous State: `Executed`
Current State: `Success`

Stdout: -
Stderr:
```
WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found

```

Exit Code: `1`


``````

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/data/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/data/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: Unknown option '-h'. Aborting.

mount info:
956 629 179:25 / /data rw,nosuid,nodev,relatime master:16 - ext4 /dev/block/platform/msm_sdcc.1/by-name/userdata rw,seclabel,discard,noauto_da_alloc,data=ordered

```
##

## Logcat Dump

`````````
$ /system/bin/logcat -d -t 3000 2>&1
--------- beginning of main
12-29 16:12:46.106 10856 10856 W Termux.SharedProperties: Not loading properties since file is null
12-29 16:12:46.115 10856 10856 I Termux.TermuxApplication: Termux files directory is accessible
12-29 16:12:46.193 10856 10856 W Termux.SharedProperties: Not loading properties since file is null
12-29 16:12:46.201 10856 10856 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-29 16:12:46.442 10856 10893 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-29 16:12:46.553 10856 10891 I ExtendedExtractor: ExtendedExtractor::create 0x0
12-29 16:12:46.580 10856 10894 I OMXClient: Using client-side OMX mux.
12-29 16:12:46.622 10856 10893 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
12-29 16:12:46.622 10856 10893 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
12-29 16:12:46.622 10856 10893 I Adreno-EGL: Build Date: 04/04/16 Mon
12-29 16:12:46.622 10856 10893 I Adreno-EGL: Local Branch: mybranch19053788
12-29 16:12:46.622 10856 10893 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.12
12-29 16:12:46.622 10856 10893 I Adreno-EGL: Local Patches: NONE
12-29 16:12:46.622 10856 10893 I Adreno-EGL: Reconstruct Branch: NOTHING
12-29 16:12:46.627 10856 10893 I OpenGLRenderer: Initialized EGL, version 1.4
12-29 16:12:46.641 10856 10894 E OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
12-29 16:12:46.663 10856 10894 D MediaOutputController: attach(0x0, 0xa92f29c0, 0xb5cd9701)
12-29 16:12:46.663 10856 10894 D MediaCodec: MediaCodec callback for event 0
12-29 16:12:46.663 10856 10894 D MediaCodec: onMediaOutputControllEvent(VIDEO_FLAGS_SET, 0x9effd55c, 4)
12-29 16:12:46.664 10856 10894 D MediaCodec: mVideoOutputFlags = 0x00000000
12-29 16:12:46.665 10856 10868 D MediaOutputController: onConnect(): 0x00010003
12-29 16:12:46.665 10856 10868 D MediaOutputController: setAudioDevicesState(0x00010003, 1)
12-29 16:12:46.665 10856 10868 D MediaOutputPolicy: notifyAudioStateIfNeeded(0x00010003)
12-29 16:12:46.665 10856 10894 D MediaOutputController: Registered as audio policy client
12-29 16:12:46.667 10856 10856 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.ExtensionTranslatingCallback>
12-29 16:12:46.667 10856 10856 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.ExtensionTranslatingCallback>
12-29 16:12:46.677 10856 10856 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$DistinctSidecarElementCallback>
12-29 16:12:46.678 10856 10856 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$DistinctSidecarElementCallback>
12-29 16:12:46.678 10856 10856 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$TranslatingCallback>
12-29 16:12:46.678 10856 10856 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$TranslatingCallback>
12-29 16:12:46.688 10856 10894 D MediaOutputController: detach(0xa92f29c0)
12-29 16:12:46.699 10856 10856 I Termux.TermuxInstaller: The termux prefix directory "/data/data/com.termux/files/usr" exists but is empty or only contains specific unimportant files.
12-29 16:12:46.734 10856 10900 I Termux.TermuxInstaller: Installing Termux bootstrap packages.
--------- beginning of system
12-29 16:12:46.735 10856 10900 W ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
12-29 16:12:46.740 10856 10900 I Termux.TermuxInstaller: Extracting bootstrap zip to prefix staging directory "/data/data/com.termux/files/usr-staging".
12-29 16:12:46.938 10856 10866 I art     : Background partial concurrent mark sweep GC freed 27734(2MB) AllocSpace objects, 2(40KB) LOS objects, 28% free, 39MB/55MB, paused 410us total 191.573ms
12-29 16:12:47.081 10856 10856 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@fca1f5d time:3968434
12-29 16:12:52.757 10856 10900 I Termux.TermuxInstaller: Moving termux prefix staging to prefix directory.
12-29 16:12:52.758 10856 10900 I Termux.TermuxInstaller: Running Termux bootstrap second stage.
12-29 16:12:52.809 10928 10928 W linker  : /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 16:12:52.842 10856 10930 V TermuxCommand: [10928-stderr] WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 16:12:52.843 10856 10930 V TermuxCommand: [10928-stderr] CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: Bootstrap Error:
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: ``````
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: (-1) Termux Bootstrap Second Stage Command:
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: Previous State: `Executed`
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: Current State: `Success`
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: 
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: Stdout: -
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: Stderr:
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: ```
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: 
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: ```
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: 
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: Exit Code: `1`
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: 
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: 
12-29 16:12:53.781 10856 10900 E Termux.TermuxInstaller: ``````
12-29 16:12:54.225 10856 10866 I art     : Background sticky concurrent mark sweep GC freed 173024(14MB) AllocSpace objects, 23(432KB) LOS objects, 27% free, 40MB/55MB, paused 634us total 120.340ms
12-29 16:12:55.222 10856 10856 I Choreographer: Skipped 60 frames!  The application may be doing too much work on its main thread.
12-29 16:13:00.869 10856 10990 I Termux.TermuxInstaller: Installing Termux bootstrap packages.
12-29 16:13:00.872 10856 10990 I Termux.TermuxInstaller: Extracting bootstrap zip to prefix staging directory "/data/data/com.termux/files/usr-staging".
12-29 16:13:05.118 10856 10990 I Termux.TermuxInstaller: Moving termux prefix staging to prefix directory.
12-29 16:13:05.119 10856 10990 I Termux.TermuxInstaller: Running Termux bootstrap second stage.
12-29 16:13:05.147 11012 11012 W linker  : /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 16:13:05.150 10856 11014 V TermuxCommand: [11012-stderr] WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 16:13:05.150 10856 11014 V TermuxCommand: [11012-stderr] CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: Bootstrap Error:
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: ``````
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: (-1) Termux Bootstrap Second Stage Command:
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: Previous State: `Executed`
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: Current State: `Success`
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: 
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: Stdout: -
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: Stderr:
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: ```
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: 
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: ```
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: 
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: Exit Code: `1`
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: 
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: 
12-29 16:13:08.514 10856 10990 E Termux.TermuxInstaller: ``````
12-29 16:13:11.090 10856 10856 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@11d9c85 time:3992444
12-29 17:40:23.090 10856 10856 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@11d9c85 time:4126123
12-29 17:40:28.441 10856 10856 E WindowManager: 
12-29 17:40:28.441 10856 10856 E WindowManager: android.view.WindowLeaked: Activity com.termux.app.TermuxActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{d0a5423 V.E...... R......D 0,0-1026,575} that was originally added here
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:372)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.app.Dialog.show(Dialog.java:326)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.app.AlertDialog$Builder.show(AlertDialog.java:1128)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at com.termux.app.TermuxInstaller.lambda$showBootstrapErrorDialog$2(TermuxInstaller.java:284)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at com.termux.app.-$$Lambda$TermuxInstaller$soi1m0BtAWIcG-Um7z34cpthUvA.run(lambda)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:739)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.os.Looper.loop(Looper.java:234)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-29 17:40:28.441 10856 10856 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-29 17:41:14.502 12910 12910 W Termux.SharedProperties: Not loading properties since file is null
12-29 17:41:14.506 12910 12910 I Termux.TermuxApplication: Termux files directory is accessible
12-29 17:41:14.560 12910 12910 W Termux.SharedProperties: Not loading properties since file is null
12-29 17:41:14.568 12910 12910 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-29 17:41:14.732 12910 12943 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-29 17:41:14.804 12910 12941 I ExtendedExtractor: ExtendedExtractor::create 0x0
12-29 17:41:14.820 12910 12944 I OMXClient: Using client-side OMX mux.
12-29 17:41:14.888 12910 12944 E OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
12-29 17:41:14.892 12910 12944 D MediaOutputController: attach(0x0, 0xa92e1380, 0xb5cd9701)
12-29 17:41:14.892 12910 12944 D MediaCodec: MediaCodec callback for event 0
12-29 17:41:14.892 12910 12944 D MediaCodec: onMediaOutputControllEvent(VIDEO_FLAGS_SET, 0x9eff855c, 4)
12-29 17:41:14.892 12910 12944 D MediaCodec: mVideoOutputFlags = 0x00000000
12-29 17:41:14.893 12910 12922 D MediaOutputController: onConnect(): 0x00010003
12-29 17:41:14.893 12910 12922 D MediaOutputController: setAudioDevicesState(0x00010003, 1)
12-29 17:41:14.893 12910 12922 D MediaOutputPolicy: notifyAudioStateIfNeeded(0x00010003)
12-29 17:41:14.893 12910 12944 D MediaOutputController: Registered as audio policy client
12-29 17:41:14.922 12910 12944 D MediaOutputController: detach(0xa92e1380)
12-29 17:41:14.933 12910 12943 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
12-29 17:41:14.933 12910 12943 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
12-29 17:41:14.933 12910 12943 I Adreno-EGL: Build Date: 04/04/16 Mon
12-29 17:41:14.933 12910 12943 I Adreno-EGL: Local Branch: mybranch19053788
12-29 17:41:14.933 12910 12943 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.12
12-29 17:41:14.933 12910 12943 I Adreno-EGL: Local Patches: NONE
12-29 17:41:14.933 12910 12943 I Adreno-EGL: Reconstruct Branch: NOTHING
12-29 17:41:14.936 12910 12943 I OpenGLRenderer: Initialized EGL, version 1.4
12-29 17:41:14.997 12910 12910 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.ExtensionTranslatingCallback>
12-29 17:41:14.997 12910 12910 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.ExtensionTranslatingCallback>
12-29 17:41:15.010 12910 12910 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$DistinctSidecarElementCallback>
12-29 17:41:15.010 12910 12910 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$DistinctSidecarElementCallback>
12-29 17:41:15.010 12910 12910 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$TranslatingCallback>
12-29 17:41:15.011 12910 12910 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.window.SidecarCompat$TranslatingCallback>
12-29 17:41:15.020 12910 12910 I Termux.TermuxInstaller: The termux prefix directory "/data/data/com.termux/files/usr" exists but is empty or only contains specific unimportant files.
12-29 17:41:15.071 12910 12951 I Termux.TermuxInstaller: Installing Termux bootstrap packages.
12-29 17:41:15.074 12910 12951 W ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
12-29 17:41:15.089 12910 12951 I Termux.TermuxInstaller: Extracting bootstrap zip to prefix staging directory "/data/data/com.termux/files/usr-staging".
12-29 17:41:15.268 12910 12919 I art     : Background partial concurrent mark sweep GC freed 28401(2MB) AllocSpace objects, 3(60KB) LOS objects, 28% free, 39MB/55MB, paused 369us total 174.150ms
12-29 17:41:15.387 12910 12910 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@fca1f5d time:4178420
12-29 17:41:20.414 12910 12951 I Termux.TermuxInstaller: Moving termux prefix staging to prefix directory.
12-29 17:41:20.414 12910 12951 I Termux.TermuxInstaller: Running Termux bootstrap second stage.
12-29 17:41:20.462 12991 12991 W linker  : /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 17:41:20.477 12910 12993 V TermuxCommand: [12991-stderr] WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 17:41:20.478 12910 12993 V TermuxCommand: [12991-stderr] CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: Bootstrap Error:
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: ``````
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: (-1) Termux Bootstrap Second Stage Command:
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: Previous State: `Executed`
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: Current State: `Success`
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: 
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: Stdout: -
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: Stderr:
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: ```
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: WARNING: linker: /data/data/com.termux/files/usr/bin/bash: unused DT entry: type 0x1d arg 0x7c04
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: 
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: ```
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: 
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: Exit Code: `1`
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: 
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: 
12-29 17:41:21.364 12910 12951 E Termux.TermuxInstaller: ``````

`````````
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.119.0-beta.1`  
**VERSION_CODE**: `1020`  
**UID**: `10311`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app:s0:c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c512,c768`  
**SE_INFO**: `default`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_7`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `3.4.0-perf-gc14c2d5`  
**SDK_INT**: `23`  
**RELEASE**: `6.0.1`  
**ID**: `23.5.A.1.291`  
**DISPLAY**: `23.5.A.1.291`  
**INCREMENTAL**: `2769308465`  
**SECURITY_PATCH**: `2016-05-01`  
**IS_DEBUGGABLE**: `0`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Sony`  
**BRAND**: `Sony`  
**MODEL**: `D6633`  
**PRODUCT**: `D6633`  
**BOARD**: `MSM8974`  
**HARDWARE**: `qcom`  
**DEVICE**: `D6633`  
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

Launch termux

### System information

* Termux application version:0.119.0-beta.1
* Android OS version: 6.0.1
* Device model: Sony D6633

**Comment by twaik** [comment]
You should not install version for Android 7+ on Android 6 device. Use appropriate version please.
