### ISSUE TITLE
Storage issues in Android 8.1

### ISSUE THREAD

**Issue by neoslaughter** [termux/termux-app#563]
Running `termux-setup-storage` just outputs the following results and doesn't asks for storage permission.

```
Exception occurred while executing:
java.lang.IllegalArgumentException: Calling application did not provide package name
        at com.android.server.am.ActivityManagerService.isInstantApp(ActivityManagerService.java:18679)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19104)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19835)
        at com.android.server.am.ActivityManagerShellCommand.runSendBroadcast(ActivityManagerShellCommand.java:621)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:154)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15014)
        at android.os.Binder.shellCommand(Binder.java:594)
        at android.os.Binder.onTransact(Binder.java:492)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4243)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
        at android.os.Binder.execTransact(Binder.java:697)
```

The issue doesn't happens in lower versions.

**Comment by neoslaughter** [comment]
I forgot mentioning that I tried giving storage permissions manually but gives the same error

**Comment by xeffyr** [comment]
termux-setup-storage and termux-api and all other script that use /system/bin/am may not work on Android 8+

**Comment by sdrausty** [comment]
My comment to possibly many Android 8 issuses.  The java version we use today, if Termux were to use the more current java, will this help in overcoming Android 8 issues?

**Comment by neoslaughter** [comment]
Well, it actually depends on the Android SDK version, IIRC

**Comment by Grimler91** [comment]
Closing this in favour of https://github.com/termux/termux-api/issues/105.
