### ISSUE TITLE
Rebuilding with apktool failed

### ISSUE THREAD

**Issue by rubikitch** [termux/termux-app#683]
I tried to use Termux as a home app,
So I tried to edit AndroidManifest.xml.

The apk file is extracted by com.pandaz.apkextraction.

But I failed to build with error.
What's wrong?

    $ apktool d Termux.0.60.apk
    I: Using Apktool 2.2.1-dirty on Termux.0.60.apk
    I: Loading resource table...
    I: Decoding AndroidManifest.xml with resources...
    I: Loading resource table from file: /home/rubikitch/.local/share/apktool/framework/1.apk
    I: Regular manifest package...
    I: Decoding file-resources...
    I: Decoding values */* XMLs...
    I: Baksmaling classes.dex...
    I: Copying assets and libs...
    I: Copying unknown files...
    I: Copying original files...

    # Edit Termux.0.6.0/AndroidManifest.xml

    $ apktool build Termux.0.60 test.apk
    I: Using Apktool 2.2.1-dirty
    I: Checking whether sources has changed...
    I: Checking whether resources has changed...
    I: Building resources...
    W: /r/compile/Termux.0.60/res/xml-v22/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutId' in package 'android'
    W: 
    W: /r/compile/Termux.0.60/res/xml-v22/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
    W: 
    Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 21, --target-sdk-version, 27, --version-code, 60, --version-name, 0.60, -F, /tmp/APKTOOL8854904712058737481.tmp, -0, arsc, -0, arsc, -I, /home/rubikitch/.local/share/apktool/framework/1.apk, -S, /r/compile/Termux.0.60/res, -M, /r/compile/Termux.0.60/AndroidManifest.xml]
            at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
            at brut.androlib.Androlib.buildResources(Androlib.java:412)
            at brut.androlib.Androlib.build(Androlib.java:311)
            at brut.androlib.Androlib.build(Androlib.java:264)
            at brut.apktool.Main.cmdBuild(Main.java:227)
            at brut.apktool.Main.main(Main.java:84)
    Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 21, --target-sdk-version, 27, --version-code, 60, --version-name, 0.60, -F, /tmp/APKTOOL8854904712058737481.tmp, -0, arsc, -0, arsc, -I, /home/rubikitch/.local/share/apktool/framework/1.apk, -S, /r/compile/Termux.0.60/res, -M, /r/compile/Termux.0.60/AndroidManifest.xml]
            at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
            at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
            ... 5 more
    Caused by: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 21, --target-sdk-version, 27, --version-code, 60, --version-name, 0.60, -F, /tmp/APKTOOL8854904712058737481.tmp, -0, arsc, -0, arsc, -I, /home/rubikitch/.local/share/apktool/framework/1.apk, -S, /r/compile/Termux.0.60/res, -M, /r/compile/Termux.0.60/AndroidManifest.xml]
            at brut.util.OS.exec(OS.java:95)
            at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
            ... 6 more

**Comment by Grimler91** [comment]
> could not exec (exit code = 1): [/usr/bin/aapt,

Looks like you are missing aapt?

**Comment by rubikitch** [comment]
$ which aapt apktool
    /usr/bin/aapt
    /usr/bin/apktool

**Comment by kosovo0275** [comment]
Here's the offending line:
    error: No resource identifier found for attribute 'shortcutId' in package 'android'

You're running a pretty old version of apktool, upgrading to the latest version should resolve your issue.

Heres the relevant commit [983e0](https://github.com/iBotPeaches/Apktool/commit/983e0ad111cd9d4aff27c8e36b5a645b99044cc5)

**Comment by rubikitch** [comment]
I just upgraded Debian/testing, but the error is not fixed.
What's wrong?

    $ aapt v; apktool --version
    Android Asset Packaging Tool, v0.2-24.0.0
    2.3.3-dirty

**Comment by l-jonas** [comment]
@rubikitch You could use Android Studio. Or is there a special reason why you have to use apktool?

**Comment by l-jonas** [comment]
Eventually it would be a nice feature to allow setting Termux as home app (extra Activity with matching Intent Filter which is disabled by default but can be enabled from the command line).

**Comment by fornwall** [comment]
I'm closing this issue as it doesn't seem to be specific to Termux. I'm also noticing the wish to use it as a Home app :).

**Comment by seisdr** [comment]
can build anything else

**Comment by yasirsaeed503374** [comment]
Error while building apk file in haxRat termux black 
ERROR Build Failed - Build Command Failed - Command failed: apkmod -r "/data/data/com.termux/files/home/haxRat/server/app/factory/decompiled" -o "/data/data/com.termux/files/home/haxrat/build.apk"
/bin/apktool: exec: line 4: /usr/lib/jvm/java-1.8-openjdk/bin/java: not found

**Comment by SDRausty** [comment]
> Eventually it would be a nice feature to allow setting Termux as home app

Setting Termux as the home app was automated in April this year when the [buildAPKs.launchers](https://buildapks.github.io/buildAPKs.launchers/) git repository was published.  Many apps can be built with [buildAPKs](https://buildapks.github.io/buildAPKs/) in Termux in a smartphone, including Termux Home Launcher.
