### ISSUE TITLE
Pudb3 (python debuger) fail to run.

### ISSUE THREAD

**Issue by BlindB0** [termux/termux-app#866]
Android 8 (On Samsung S7), no  root
Latest Termux
Install puthon and pip over "pkg install"
Install Pudb over pip.
Without code to debug - pudb runs with standard help output.
With any code - crash with traceback:

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/__init__.py", line 119, in runscript
    dbg._runscript(mainpyfile)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 457, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/data/data/com.termux/files/usr/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "tst.py", line 1, in <module>
    print('hello world!')
  File "tst.py", line 1, in <module>
    print('hello world!')
  File "/data/data/com.termux/files/usr/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 187, in dispatch_line
    self.user_line(frame)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 408, in user_line
    self.interaction(frame)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 376, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 2116, in call_with_ui
    self.show()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 2107, in show
    self.screen.start()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urwid/display_common.py", line 751, in start
    self._start(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 222, in _start
    tty.setcbreak(fd)
  File "/data/data/com.termux/files/usr/lib/python3.6/tty.py", line 36, in setcbreak
    tcsetattr(fd, when, mode)
termios.error: (13, 'Permission denied')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pudb3", line 11, in <module>
    load_entry_point('pudb==2018.1', 'console_scripts', 'pudb3')()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/run.py", line 34, in main
    steal_output=options.steal_output)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/__init__.py", line 126, in runscript
    dbg.interaction(None, sys.exc_info())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 376, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 2116, in call_with_ui
    self.show()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pudb/debugger.py", line 2107, in show
    self.screen.start()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urwid/display_common.py", line 751, in start
    self._start(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 222, in _start
    tty.setcbreak(fd)
  File "/data/data/com.termux/files/usr/lib/python3.6/tty.py", line 36, in setcbreak
    tcsetattr(fd, when, mode)
termios.error: (13, 'Permission denied')
```

**Comment by Grimler91** [comment]
Android probably blocks the tcsetattr call, apt had a similar problem: https://github.com/termux/termux-packages/issues/1359

**Comment by Grimler91** [comment]
I would suggest that you open an issue upstream in the pudb repo: https://github.com/inducer/pudb
