### ISSUE TITLE
File "<script>", line 339, in idteman                     NameError: global name 'id_teman' is not defined            $

### ISSUE THREAD

**Issue by bmvaghera** [termux/termux-app#894]
*] Mengambil 3 id teman                                    Traceback (most recent call last):                            File "MBF2.pye", line 1, in <module>                        File "<script>", line 12, in <module>                       File "<script>", line 12, in <module>                       File "<script>", line 407, in <module>                      File "<script>", line 400, in menu                          File "<script>", line 339, in idteman                     NameError: global name 'id_teman' is not defined            $

Im new plz intrction step by step

**Comment by xeffyr** [comment]
We don't know what is MFB2.pye and where you get it. Ask author of this file instead. We do not accepting issues for such things here, nor instructioning how to use them.

@Grimler91 This can be closed.

**Comment by Grimler91** [comment]
And don't spam the repo with duplicate issues..

**Comment by alvingardan** [comment]
Traceback (most recent call last):
  File "MBF2.pye", line 1, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 407, in <module>
  File "<script>", line 400, in menu
  File "<script>", line 327, in idteman
  File "<script>", line 254, in login
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 620, in select_form
    global_form = self._factory.global_form
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 266, in global_form
    self.forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 273, in forms
    self._current_forms, self._current_global_form = self._get_forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 288, in _get_forms
    if self.root is None:
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 253, in root
    response, verify=False))
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 153, in content_parser
    return parse(data, **kw)
