### ISSUE TITLE
Termux Android Things Crash First Launch

### ISSUE THREAD

**Issue by brubakerjeff** [termux/termux-app#961]
Hi,

We are running Termux on Android Things 1.07. We are successfully able to auto launch (PR coming soon to simplify actions inside of Manifest as there are currently) Termux however upon what appears to be first launch the program stops responding. We captured the logcat. Any insight or pointers would be appreciated as we start deep diving.

--------- beginning of crash
12-25 17:41:04.779   876   876 E AndroidRuntime: FATAL EXCEPTION: main
12-25 17:41:04.779   876   876 E AndroidRuntime: Process: com.termux, PID: 876
12-25 17:41:04.779   876   876 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.termux.terminal.f.f()' on a null object reference
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at com.termux.view.c.a(SourceFile:59)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at com.termux.view.TerminalView.onDraw(SourceFile:768)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19192)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19062)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.drawChild(SourceFile:1426)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19060)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19060)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19060)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19060)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.View.draw(View.java:19195)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:788)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3105)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3019)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-25 17:41:04.779   876   876 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-25 17:41:15.878  1130  1150 V NuMediaExtractor: setDataSource fd=32 (/oem/app/com.termux/app.apk), offset=189768, length=5090
12-25 17:41:16.066  1130  1150 V NuMediaExtractor: track of type 'audio/vorbis' does not publish bitrate
12-25 17:41:16.947  1130  1130 D vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
12-25 17:41:17.340  1130  1130 D OpenGLRenderer: HWUI GL Pipeline
12-25 17:41:20.695  1339  1339 I termux  : No files to execute at boot

**Comment by seisdr** [comment]
I was want to write something,. sorry
